// AUTO-GENERATED by scripts/buildExtraFilms.ts — do not edit by hand.
// Catalogue expansion (21 films). Editorial text is ORIGINAL
// (see scripts/newFilmsData*.ts); factual metadata enriched from Wikidata.
import type { SeedFilm } from "./films";

export const extraFilms2: SeedFilm[] = [
  {
    "slug": "beware-of-the-car",
    "title": "Beware of the Car",
    "original": "Берегись автомобиля",
    "year": 1966,
    "country": "USSR",
    "studio": "Mosfilm",
    "director": "Eldar Ryazanov",
    "cast": [
      "Innokenty Smoktunovsky",
      "Anatoly Papanov",
      "Andrei Mironov",
      "Oleg Yefremov"
    ],
    "genres": [
      "Comedy",
      "Crime",
      "Satire"
    ],
    "runtime": 94,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "Yuri Detochkin, a gentle, scrupulously honest insurance agent, leads a secret double life as a car thief, but he steals only from crooks and profiteers and gives the proceeds to orphanages. A friend who happens to be a traffic detective slowly closes in on him, torn between duty and admiration. The film follows this Soviet Robin Hood toward an arrest and trial that ask whether the law can quite reach a man who breaks it only to do good.",
    "context": "One of Eldar Ryazanov's best-loved comedies, written with Emil Braginsky, it blends gentle farce with sharp satire of the petty corruption of the consumer-minded 1960s. Innokenty Smoktunovsky plays Detochkin as a kind of holy fool, and the cast is a roll-call of comic talent, from Anatoly Papanov to a young Andrei Mironov. Its mix of warmth, melancholy and social critique set the template for Ryazanov's later tragicomedies.",
    "themes": [
      "justice and the law",
      "the holy fool",
      "modern morality"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Beware_of_the_Car",
    "starterClassic": true,
    "wikidataId": "Q1272202"
  },
  {
    "slug": "the-forty-first",
    "title": "The Forty-First",
    "original": "Сорок первый",
    "year": 1956,
    "country": "USSR",
    "studio": "Mosfilm",
    "director": "Grigori Chukhrai",
    "cast": [
      "Izolda Izvitskaya",
      "Oleg Strizhenov"
    ],
    "genres": [
      "War",
      "Drama",
      "Romance"
    ],
    "runtime": 88,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "During the Russian Civil War, a crack Red Army sniper named Maryutka, who has killed forty White soldiers, is charged with guarding a captured White officer as her unit crosses the desert and a deserted Caspian island. Marooned alone together, the two enemies fall in love. When a White ship finally appears, her loyalty and her heart collide, and the officer becomes her forty-first shot.",
    "context": "Grigori Chukhrai's debut feature, a remake of a 1927 silent, was a landmark of the Thaw for daring to give a White officer genuine humanity and to put private love above ideological duty. Its lyrical colour photography and island setting won it a special prize at Cannes. The film helped open Soviet cinema to a more humane, ambiguous treatment of the Civil War.",
    "themes": [
      "love across enemy lines",
      "duty vs. feeling",
      "the Civil War"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/The_Forty-First_(1956_film)",
    "wikidataId": "Q2445353"
  },
  {
    "slug": "clear-sky",
    "title": "Clear Sky",
    "original": "Чистое небо",
    "year": 1961,
    "country": "USSR",
    "studio": "Mosfilm",
    "director": "Grigori Chukhrai",
    "cast": [
      "Yevgeny Urbansky",
      "Nina Drobysheva"
    ],
    "genres": [
      "Drama",
      "War",
      "Romance"
    ],
    "runtime": 110,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "A celebrated test pilot is shot down and taken prisoner during the war, and on his return home he is stripped of his Party card and his standing, treated as a suspect rather than a hero. The woman who loves him stands by him through years of disgrace. Only after Stalin's death does the thaw finally restore his honour and his wings.",
    "context": "Made at the height of the cultural Thaw, Chukhrai's film was unusually direct in condemning the suspicion heaped on former prisoners of war and the wider climate of fear under Stalin. Yevgeny Urbansky gave one of his signature performances as the grounded pilot. Its imagery of ice breaking on a river became a famous metaphor for the era's loosening grip.",
    "themes": [
      "loyalty",
      "rehabilitation",
      "the Thaw"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Clear_Skies_(film)",
    "wikidataId": "Q2394071"
  },
  {
    "slug": "agony",
    "title": "Agony",
    "original": "Агония",
    "year": 1981,
    "country": "USSR",
    "studio": "Mosfilm",
    "director": "Elem Klimov",
    "cast": [
      "Aleksei Petrenko",
      "Anatoly Romashin",
      "Velta Line"
    ],
    "genres": [
      "Historical epic",
      "Drama",
      "Biography"
    ],
    "runtime": 148,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "On the eve of the 1917 revolution, the peasant mystic Grigori Rasputin holds a strange power over the Tsarina and, through her, over the crumbling court of Nicholas II. The film charts his drunken, ecstatic excesses and the desperate conspiracy of noblemen who set out to murder him. Around this grotesque central figure, the Romanov dynasty slides toward its end.",
    "context": "Elem Klimov shot the film in the mid-1970s, but its lurid portrait of the imperial court and its near-sympathetic complexity unsettled the authorities, who held it back for years before a limited release. Aleksei Petrenko's volcanic performance as Rasputin anchors a feverish, almost hallucinatory historical canvas. It stands among the boldest Soviet films about the end of the old regime.",
    "themes": [
      "decadence",
      "power and superstition",
      "the fall of an empire"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Agony_(1981_film)",
    "wikidataId": "Q395279"
  },
  {
    "slug": "uncle-vanya",
    "title": "Uncle Vanya",
    "original": "Дядя Ваня",
    "year": 1970,
    "country": "USSR",
    "studio": "Mosfilm",
    "director": "Andrei Konchalovsky",
    "cast": [
      "Innokenty Smoktunovsky",
      "Sergei Bondarchuk",
      "Irina Kupchenko"
    ],
    "genres": [
      "Drama",
      "Literary adaptation"
    ],
    "runtime": 104,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "On a decaying country estate, the long-suffering Vanya and his niece Sonya have sacrificed their lives to support a self-important retired professor, only to realize how little he was worth. The arrival of the professor, his beautiful young wife, and a world-weary local doctor stirs up frustrated love and bitter regret among them all. By the end the visitors leave and the two who remain face a future of endurance.",
    "context": "Andrei Konchalovsky's faithful, finely acted adaptation of Chekhov's play gathers a remarkable cast, with Innokenty Smoktunovsky as the doctor Astrov and Sergei Bondarchuk as Vanya. Konchalovsky uses shifts between colour and monochrome and close, searching camerawork to bring out the play's mood of thwarted lives. It is regarded as one of the finest screen Chekhovs.",
    "themes": [
      "wasted lives",
      "longing",
      "disillusion"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Uncle_Vanya_(1970_film)",
    "wikidataId": "Q1549483"
  },
  {
    "slug": "nine-days-of-one-year",
    "title": "Nine Days of One Year",
    "original": "Девять дней одного года",
    "year": 1962,
    "country": "USSR",
    "studio": "Mosfilm",
    "director": "Mikhail Romm",
    "cast": [
      "Aleksey Batalov",
      "Innokenty Smoktunovsky",
      "Tatyana Lavrova"
    ],
    "genres": [
      "Drama"
    ],
    "runtime": 111,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "Two nuclear physicists, the idealistic Gusev and the sceptical, witty Kulikov, are close friends and rivals for the same woman. Gusev keeps working despite a dangerous dose of radiation that may cost him his life, convinced the research is worth the risk. The film follows their friendship, their debates about the meaning of science, and the quiet courage of a man facing his own mortality.",
    "context": "Mikhail Romm's spare, modernist drama captured the optimism and anxiety of the early atomic age and the prestige of physics during the Thaw. Its cool, intellectual style and the sparkling performances of Aleksey Batalov and Innokenty Smoktunovsky made it hugely influential on a younger generation of Soviet filmmakers, several of whom were Romm's students.",
    "impact": "Widely admired for its restrained, intellectual approach, it influenced the look and tone of 1960s Soviet cinema, and Romm's teaching at VGIK shaped directors such as Tarkovsky, Shukshin and Konchalovsky.",
    "themes": [
      "science and sacrifice",
      "friendship",
      "the atomic age"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Nine_Days_in_One_Year",
    "wikidataId": "Q1530651"
  },
  {
    "slug": "five-evenings",
    "title": "Five Evenings",
    "original": "Пять вечеров",
    "year": 1979,
    "country": "USSR",
    "studio": "Mosfilm",
    "director": "Nikita Mikhalkov",
    "cast": [
      "Lyudmila Gurchenko",
      "Stanislav Lyubshin"
    ],
    "genres": [
      "Drama",
      "Romance"
    ],
    "runtime": 98,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "Over five evenings, a middle-aged man and the woman he loved and left eighteen years earlier, before the war separated them, cautiously rediscover one another in a cramped Moscow apartment. Old wounds, pride and small deceptions get in the way before they reach a fragile reconciliation. The whole drama unfolds in a handful of rooms.",
    "context": "Nikita Mikhalkov shot this intimate chamber piece quickly, between larger productions, adapting a play by Aleksandr Volodin. Its warmth and restraint, and the finely matched performances of Lyudmila Gurchenko and Stanislav Lyubshin, made it one of the most beloved Soviet films about ordinary love and the passage of time.",
    "themes": [
      "second chances",
      "lost time",
      "tenderness"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Five_Evenings",
    "wikidataId": "Q2972912"
  },
  {
    "slug": "kinfolk",
    "title": "Kinfolk",
    "original": "Родня",
    "year": 1981,
    "country": "USSR",
    "studio": "Mosfilm",
    "director": "Nikita Mikhalkov",
    "cast": [
      "Nonna Mordyukova",
      "Svetlana Kryuchkova",
      "Yuri Bogatyryov"
    ],
    "genres": [
      "Comedy",
      "Drama"
    ],
    "runtime": 98,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "A hearty, bewildered village woman travels to the city to visit her daughter, hoping to mend the young woman's broken marriage, and collides with a modern urban life she cannot fathom. Her well-meaning interference upends everyone around her. Beneath the comedy runs a sharp look at the gulf between the old rural world and the restless, fractured city.",
    "context": "A change of register for Nikita Mikhalkov, this satirical tragicomedy is carried by Nonna Mordyukova's towering performance as the mother. Its grotesque, almost absurdist touches and its portrait of late-Soviet social drift gave it a bite unusual for a popular comedy, and it featured the screen debut of a young Oleg Menshikov.",
    "themes": [
      "family",
      "town and country",
      "modern alienation"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Family_Relations",
    "wikidataId": "Q4395981"
  },
  {
    "slug": "dont-grieve",
    "title": "Don't Grieve!",
    "original": "Не горюй!",
    "year": 1969,
    "country": "USSR (Georgian SSR)",
    "studio": "Mosfilm",
    "director": "Georgiy Daneliya",
    "cast": [
      "Vakhtang Kikabidze",
      "Sofiko Chiaureli",
      "Sergo Zakariadze"
    ],
    "genres": [
      "Comedy",
      "Drama"
    ],
    "runtime": 94,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "In a Georgian town at the turn of the twentieth century, a warm-hearted young doctor moves among his neighbours through a string of feasts, quarrels, romances and funerals, embracing life in all its comedy and grief. The film is less a plot than a garland of episodes celebrating friendship, music and the bittersweet flavour of existence.",
    "context": "Georgiy Daneliya, himself Georgian, transplanted a French novel to his homeland for this sun-warmed tragicomedy, full of song and feeling. Vakhtang Kikabidze, later the star of Mimino, leads a vivid Georgian cast. The film distils Daneliya's gift for finding sorrow inside laughter and laughter inside sorrow.",
    "themes": [
      "joy and sorrow",
      "community",
      "the fullness of life"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Don't_Grieve",
    "wikidataId": "Q2003684"
  },
  {
    "slug": "the-stone-flower",
    "title": "The Stone Flower",
    "original": "Каменный цветок",
    "year": 1946,
    "country": "USSR",
    "studio": "Mosfilm",
    "director": "Aleksandr Ptushko",
    "cast": [
      "Vladimir Druzhnikov",
      "Tamara Makarova",
      "Mikhail Troyanovsky"
    ],
    "genres": [
      "Fantasy",
      "Fairy tale",
      "Drama"
    ],
    "runtime": 82,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "A gifted young stonecutter in the Ural mountains becomes obsessed with carving a malachite flower of perfect, living beauty, and is lured into the underground domain of the Mistress of the Copper Mountain, who tests his art and his heart. His faithful betrothed waits above, fearing she has lost him to the mountain's enchantment.",
    "context": "Drawn from Pavel Bazhov's Ural folk tales, The Stone Flower was one of the first Soviet films shot in colour, and its rich palette won Aleksandr Ptushko a prize at the first postwar Cannes festival. It launched his long career of bringing Russian folklore to the screen with lavish craft and spectacle.",
    "themes": [
      "art and obsession",
      "nature's magic",
      "true love"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/The_Stone_Flower_(1946_film)",
    "wikidataId": "Q1219544"
  },
  {
    "slug": "white-bim-black-ear",
    "title": "White Bim Black Ear",
    "original": "Белый Бим Чёрное ухо",
    "year": 1977,
    "country": "USSR",
    "studio": "Gorky Film Studio",
    "director": "Stanislav Rostotsky",
    "cast": [
      "Vyacheslav Tikhonov",
      "Valentina Vladimirova",
      "Mikhail Dadyko"
    ],
    "genres": [
      "Drama",
      "Family"
    ],
    "runtime": 172,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "When his gentle, ailing owner is taken to hospital, a loyal setter named Bim sets out across the city to find him, encountering kindness and cruelty in turn from the people he meets. The dog's search becomes a moving portrait of human decency and indifference. Its quiet heartbreak has reduced generations of viewers to tears.",
    "context": "Stanislav Rostotsky adapted Gavriil Troyepolsky's novel into one of the most beloved Soviet family dramas, anchored by Vyacheslav Tikhonov as Bim's devoted master. The film was nominated for the Academy Award for Best Foreign Language Film and remains a fixture of childhood viewing across the former Soviet world.",
    "themes": [
      "loyalty",
      "kindness and cruelty",
      "devotion"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Gorky Film Studio official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/White_Bim_Black_Ear",
    "starterClassic": true,
    "wikidataId": "Q1635046"
  },
  {
    "slug": "well-live-till-monday",
    "title": "We'll Live Till Monday",
    "original": "Доживём до понедельника",
    "year": 1968,
    "country": "USSR",
    "studio": "Gorky Film Studio",
    "director": "Stanislav Rostotsky",
    "cast": [
      "Vyacheslav Tikhonov",
      "Olga Ostroumova",
      "Nina Menshikova"
    ],
    "genres": [
      "Drama"
    ],
    "runtime": 106,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "Over three days at a Moscow school, a thoughtful, demanding history teacher questions his vocation and his place among colleagues and pupils, while a young teacher and the students wrestle with honesty, first love and what it means to live decently. A schoolchild's essay on happiness becomes the film's quiet moral centre.",
    "context": "Stanislav Rostotsky's sensitive school drama struck a deep chord during the Thaw's later years for taking young people and their moral questions seriously. Vyacheslav Tikhonov's restrained teacher and Olga Ostroumova's screen debut helped make it a touchstone, and it won the top prize at the Moscow International Film Festival.",
    "themes": [
      "teaching and conscience",
      "generations",
      "honesty"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Gorky Film Studio official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/We'll_Live_Till_Monday",
    "wikidataId": "Q1284566"
  },
  {
    "slug": "kingdom-of-crooked-mirrors",
    "title": "Kingdom of Crooked Mirrors",
    "original": "Королевство кривых зеркал",
    "year": 1963,
    "country": "USSR",
    "studio": "Gorky Film Studio",
    "director": "Aleksandr Rou",
    "cast": [
      "Olga Yukina",
      "Tatyana Yukina",
      "Andrei Stapran"
    ],
    "genres": [
      "Fantasy",
      "Fairy tale",
      "Family"
    ],
    "runtime": 75,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "A careless, lazy girl named Olya steps through a magic mirror and meets her own reversed reflection, Yalo, in a topsy-turvy kingdom where crooked mirrors hide the truth and the people are kept from seeing how they really live. Together the two girls help free an imprisoned mirror-maker and learn to face their own faults.",
    "context": "Aleksandr Rou's inventive fairy-tale film, with its playful doubling of twin actresses and its sly allegory about distorted truth, became a children's favourite. It is a fine example of the rich tradition of Soviet fantasy filmmaking that Rou did so much to shape.",
    "themes": [
      "seeing clearly",
      "courage",
      "self-knowledge"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Gorky Film Studio official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Kingdom_of_Crooked_Mirrors",
    "wikidataId": "Q194941"
  },
  {
    "slug": "fire-water-and-brass-pipes",
    "title": "Fire, Water and Brass Pipes",
    "original": "Огонь, вода и… медные трубы",
    "year": 1968,
    "country": "USSR",
    "studio": "Gorky Film Studio",
    "director": "Aleksandr Rou",
    "cast": [
      "Natalya Sedykh",
      "Aleksei Katyshev",
      "Georgy Millyar"
    ],
    "genres": [
      "Fantasy",
      "Fairy tale",
      "Family"
    ],
    "runtime": 81,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "A young charcoal-burner and his sweetheart are parted when she is carried off by the wicked sorcerer Kashchei, and he must pass through fire, water and the 'brass pipes' of fame and flattery to win her back. The trials test not only his courage but his faithfulness and his head.",
    "context": "One of Aleksandr Rou's exuberant later fairy tales, it reunites him with the young Natalya Sedykh of Morozko and the great character actor Georgy Millyar, long the studio's favourite Baba Yaga and Kashchei. Its folk creatures, songs and gentle moral lessons place it firmly in the beloved Soviet fairy-tale tradition.",
    "themes": [
      "constancy",
      "temptation",
      "true love"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Gorky Film Studio official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Fire%2C_Water%2C_and_Brass_Pipes",
    "wikidataId": "Q932464"
  },
  {
    "slug": "the-golden-antelope",
    "title": "The Golden Antelope",
    "original": "Золотая антилопа",
    "year": 1954,
    "country": "USSR",
    "studio": "Soyuzmultfilm",
    "director": "Lev Atamanov",
    "cast": [],
    "genres": [
      "Animation",
      "Fairy tale",
      "Family"
    ],
    "runtime": 31,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "A magical antelope whose hooves strike gold from the ground befriends a poor orphan boy and protects him from a greedy raja who wants endless riches. When the raja's lust for gold overwhelms him, the antelope grants his wish in a way that destroys him. Set in an Indian fairy-tale world, the film is a fable about the difference between need and greed.",
    "context": "Lev Atamanov's beautifully drawn film, made at Soyuzmultfilm in the lush style of the studio's golden age, is admired for its graceful animation and its stylised Indian setting. It stands alongside his Snow Queen and Scarlet Flower as a high point of classic Soviet animation.",
    "themes": [
      "greed",
      "kindness",
      "freedom"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Soyuzmultfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/The_Golden_Antelope",
    "wikidataId": "Q4193204"
  },
  {
    "slug": "to-kill-a-dragon",
    "title": "To Kill a Dragon",
    "original": "Убить дракона",
    "year": 1988,
    "country": "USSR / Germany",
    "studio": "Mosfilm",
    "director": "Mark Zakharov",
    "cast": [
      "Oleg Yankovsky",
      "Aleksandr Abdulov",
      "Yevgeny Leonov"
    ],
    "genres": [
      "Fantasy",
      "Drama",
      "Satire"
    ],
    "runtime": 116,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "A wandering knight named Lancelot arrives in a town that has lived for centuries under the rule of a shape-shifting Dragon, and resolves to free its people, only to find that the townsfolk have grown comfortable with their servitude. Even after the Dragon is slain, a new tyrant rises from among them, and Lancelot learns that the hardest dragon to kill is the one inside ordinary hearts.",
    "context": "Mark Zakharov's dark, carnivalesque fantasy, adapted from Yevgeny Schwartz's allegorical play, arrived at the height of perestroika and was widely read as a parable about tyranny and the people's complicity in it. Reuniting Zakharov's regular players Oleg Yankovsky, Aleksandr Abdulov and Yevgeny Leonov, it is a fitting capstone to his cycle of philosophical fairy tales.",
    "themes": [
      "tyranny and freedom",
      "complicity",
      "the dragon within"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Mosfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/To_Kill_a_Dragon",
    "wikidataId": "Q4468674"
  },
  {
    "slug": "don-quixote",
    "title": "Don Quixote",
    "original": "Дон Кихот",
    "year": 1957,
    "country": "USSR",
    "studio": "Lenfilm",
    "director": "Grigori Kozintsev",
    "cast": [
      "Nikolai Cherkasov",
      "Yuri Tolubeyev"
    ],
    "genres": [
      "Drama",
      "Literary adaptation",
      "Adventure"
    ],
    "runtime": 94,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "The gaunt, gentle country gentleman Don Quixote, his head turned by tales of chivalry, sets out with his earthy squire Sancho Panza to right the world's wrongs as a knight errant. He tilts at windmills and mistakes inns for castles, mocked by all yet somehow nobler than the sane world around him. His doomed idealism is both absurd and deeply moving.",
    "context": "Grigori Kozintsev's widescreen colour adaptation of Cervantes, made before his celebrated Shakespeare films, gave Nikolai Cherkasov one of his great late roles as the knight of the sorrowful countenance. Sympathetic and humane, it reads Quixote's madness as a kind of grace, and ranks among the finest screen versions of the novel.",
    "themes": [
      "idealism",
      "madness and nobility",
      "illusion"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Lenfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Don_Quixote_(1957_film)",
    "wikidataId": "Q518901"
  },
  {
    "slug": "trial-on-the-road",
    "title": "Trial on the Road",
    "original": "Проверка на дорогах",
    "year": 1971,
    "country": "USSR",
    "studio": "Lenfilm",
    "director": "Aleksei German",
    "cast": [
      "Rolan Bykov",
      "Anatoly Solonitsyn",
      "Vladimir Zamansky"
    ],
    "genres": [
      "War",
      "Drama"
    ],
    "runtime": 96,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "During the war, a Soviet soldier who had surrendered and served with the Germans gives himself up to a partisan band and begs the chance to redeem himself. The wary partisan commander must decide whether to trust him, while his hard-line commissar wants the defector shot. A dangerous raid on a German supply train becomes the man's trial and his chance at atonement.",
    "context": "Aleksei German's early feature dared to take a former collaborator as its sympathetic hero, and its morally complex view of the war led the authorities to ban it for fifteen years before its release during glasnost. Its gritty, unheroic realism and fine ensemble, including Rolan Bykov and Anatoly Solonitsyn, mark it as an early work of one of Russia's most uncompromising directors.",
    "themes": [
      "redemption",
      "guilt",
      "moral ambiguity"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Lenfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Trial_on_the_Road",
    "wikidataId": "Q3213961"
  },
  {
    "slug": "the-star-of-captivating-happiness",
    "title": "The Star of Captivating Happiness",
    "original": "Звезда пленительного счастья",
    "year": 1975,
    "country": "USSR",
    "studio": "Lenfilm",
    "director": "Vladimir Motyl",
    "cast": [
      "Irina Kupchenko",
      "Oleg Strizhenov",
      "Oleg Yankovsky"
    ],
    "genres": [
      "Historical epic",
      "Drama",
      "Romance"
    ],
    "runtime": 160,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "After the failed Decembrist uprising of 1825, several noblewomen give up their titles, wealth and comfort to follow their condemned husbands into Siberian exile and hard labour. The film interweaves the doomed revolt with the women's extraordinary acts of loyalty, tracing love and conscience against the machinery of the autocratic state.",
    "context": "Vladimir Motyl, fresh from the popular White Sun of the Desert, turned to history for this lavish, romantic epic about the Decembrists and the wives who shared their fate. Its sweeping period staging and a starry cast, including Oleg Yankovsky and Innokenty Smoktunovsky, made it a much-loved film about idealism and sacrifice.",
    "themes": [
      "devotion",
      "sacrifice",
      "conscience"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Lenfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/The_Star_of_Captivating_Happiness",
    "wikidataId": "Q4189412"
  },
  {
    "slug": "dead-season",
    "title": "Dead Season",
    "original": "Мёртвый сезон",
    "year": 1968,
    "country": "USSR",
    "studio": "Lenfilm",
    "director": "Savva Kulish",
    "cast": [
      "Donatas Banionis",
      "Rolan Bykov",
      "Svetlana Korkoshko"
    ],
    "genres": [
      "Drama",
      "Crime"
    ],
    "runtime": 138,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "A Soviet intelligence officer is sent into the West on a dangerous mission to track down a former Nazi scientist who experimented with nerve agents, and to arrange a spy exchange. Cool and methodical, he navigates a shadow world of surveillance and betrayal where a single mistake means death. The film is a sober, intelligent portrait of the loneliness of the secret agent.",
    "context": "Savva Kulish's restrained spy thriller, loosely inspired by real intelligence operations and introduced on screen by the famous spy Rudolf Abel, was a major popular success and a more thoughtful, melancholy answer to Western spy films. Donatas Banionis, later the lead of Tarkovsky's Solaris, gives the agent a quiet, weary humanity.",
    "themes": [
      "espionage",
      "conscience",
      "the Cold War"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Lenfilm official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Dead_Season",
    "wikidataId": "Q281297"
  },
  {
    "slug": "the-magic-lamp-of-aladdin",
    "title": "The Magic Lamp of Aladdin",
    "original": "Волшебная лампа Аладдина",
    "year": 1966,
    "country": "USSR",
    "studio": "Gorky Film Studio",
    "director": "Boris Rytsarev",
    "cast": [
      "Boris Bystrov",
      "Dodo Chogovadze",
      "Andrei Fayt"
    ],
    "genres": [
      "Fantasy",
      "Fairy tale",
      "Family"
    ],
    "runtime": 69,
    "subs": [
      "English",
      "Russian"
    ],
    "summary": "In a fairy-tale Baghdad, the poor but good-hearted youth Aladdin is singled out by a sinister visiting magician who tricks him into fetching an old lamp from an enchanted cave. Trapped underground, Aladdin discovers that the lamp summons a mighty genie able to grant any wish, and with its help he wins the hand of the Sultan's daughter, Princess Budur. When the magician steals the lamp and carries off the princess, Aladdin must use his wits rather than magic to win back both his love and his fortune.",
    "context": "Boris Rytsarev's colourful adaptation of the tale from the Thousand and One Nights was made at the Gorky Film Studio, long the home of Soviet children's and fairy-tale cinema. Shot in a stylised Arabian setting with bright costumes, magic effects and a gentle moral about humility and kindness, it became a perennial favourite for young audiences across the Soviet Union.",
    "themes": [
      "wishes",
      "humility",
      "good versus evil"
    ],
    "watch": [
      {
        "platform": "YouTube",
        "label": "Gorky Film Studio official channel",
        "sourceType": "OFFICIAL",
        "rightsNote": "Released free & legal by the studio. Confirm the exact video link before production."
      }
    ],
    "wikipediaUrl": "https://en.wikipedia.org/wiki/Aladdin_and_His_Magic_Lamp_(1967_film)",
    "wikidataId": "Q247713"
  }
];
