// AUTO-GENERATED by scripts/fetch-images.ts — do not edit by hand.
// Freely-licensed Wikimedia Commons images for films and people, plus
// official-studio YouTube thumbnails as a last resort (see youtube-thumbs.ts).

export type ImageRecord = {
  url: string;
  descriptionUrl: string;
  licenseName: string;
  licenseUrl?: string;
  attribution: string;
};

export const filmImages: Record<string, ImageRecord> = {
  "the-cranes-are-flying": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/89/The_Cranes_Are_Flying_-_US_release_poster.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:The_Cranes_Are_Flying_-_US_release_poster.jpg",
    "licenseName": "Public domain",
    "attribution": "John J. Lomasney / Heritage Auctions"
  },
  "hedgehog-in-the-fog": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/1b/The_Soviet_Union_1988_CPA_5919_stamp_%28Hedgehog_in_the_Fog%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:The_Soviet_Union_1988_CPA_5919_stamp_(Hedgehog_in_the_Fog).jpg",
    "licenseName": "Public domain",
    "attribution": "USSR Post / Scanned 600 dpi by User Matsievsky from personal collection"
  },
  "battleship-potemkin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Battleship_Potemkin-Ship_portrait.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Battleship_Potemkin-Ship_portrait.jpg",
    "licenseName": "Public domain",
    "attribution": "SM Eisenstein / [1]"
  },
  "man-with-a-movie-camera": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Man_with_a_movie_camera_1929_2.png",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Man_with_a_movie_camera_1929_2.png",
    "licenseName": "Public domain",
    "attribution": "Dziga Vertov / http://anthologyfilmarchives.org/collections/reference-library/stills/683"
  },
  "war-and-peace": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c1/War_and_Peace_%281967%2C_Russia%29_movie_script.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:War_and_Peace_(1967,_Russia)_movie_script.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "shakko / Own work"
  },
  "dersu-uzala": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/48/Dersuuzala.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Dersuuzala.jpg",
    "licenseName": "Public domain",
    "attribution": "Vladimir Arsenyev / Владимир Клавдиевич Арсеньев. Собрание сочинений в 6 томах. Том I. / Под ред. ОИАК. — Владивосток, Альманах «Рубеж», 2007. — 704 с."
  },
  "the-irony-of-fate": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/1f/File_by_Alexander_Baranov_-_%D0%A1_%D0%9D%D0%BE%D0%B2%D1%8B%D0%BC_%D0%B3%D0%BE%D0%B4%D0%BE%D0%BC%21_%2811677507426%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:File_by_Alexander_Baranov_-_%D0%A1_%D0%9D%D0%BE%D0%B2%D1%8B%D0%BC_%D0%B3%D0%BE%D0%B4%D0%BE%D0%BC!_(11677507426).jpg",
    "licenseName": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "attribution": "Alexander Baranov from Montpellier, France / С Новым годом!"
  },
  "office-romance": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/12/Office_Romance_crew_05.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Office_Romance_crew_05.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "mos.ru / https://www.mos.ru/news/item/72911073/"
  },
  "operation-y-and-shuriks-other-adventures": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/24/Arkhangelskoye_Vadim_Zadorozhnys_Vehicle_Museum_S-3A_IMG_9619_2150.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Arkhangelskoye_Vadim_Zadorozhnys_Vehicle_Museum_S-3A_IMG_9619_2150.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Alexxx1979 / Own work"
  },
  "kin-dza-dza": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Pepelac2010.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Pepelac2010.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Pycckue / Own work"
  },
  "alexander-nevsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/74/Nevski3.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Nevski3.jpg",
    "licenseName": "Public domain",
    "attribution": "Sergey Eisenstein / Russian Wikipedia, original description was/is here"
  },
  "hamlet": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f4/1966_CPA_3328.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:1966_CPA_3328.jpg",
    "licenseName": "Public domain",
    "attribution": "Почта СССР / http://blog.imhonet.ru/author/svanass22/post/5392080/"
  },
  "a-cruel-romance": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Ryazanov_crew_1983.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Ryazanov_crew_1983.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Igor Gnevashev / https://www.mos.ru/news/item/134732073/"
  },
  "a-railway-station-for-two": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Crew_of_Station_for_Two_with_actors.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Crew_of_Station_for_Two_with_actors.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Главархив Москвы / https://www.mos.ru/news/item/112127073/"
  },
  "the-garage": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Semyon_Farada_1979.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Semyon_Farada_1979.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Igor Gnevashev / https://www.mos.ru/news/item/151611073/"
  },
  "cheburashka-and-gena-the-crocodile": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/fa/The_Soviet_Union_1988_CPA_5917_stamp_%28Gena_the_Crocodile._Cheburashka._Shapoklyak%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:The_Soviet_Union_1988_CPA_5917_stamp_(Gena_the_Crocodile._Cheburashka._Shapoklyak).jpg",
    "licenseName": "Public domain",
    "attribution": "USSR Post / Scanned 600 dpi by User Matsievsky from personal collection"
  },
  "winnie-the-pooh": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/29/Russian_Pooh_and_Piglet_postcard_%28cropped%29.png",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Russian_Pooh_and_Piglet_postcard_(cropped).png",
    "licenseName": "Public domain",
    "attribution": "Ministry of Communications of the USSR / Self-scanned, Private collection Weshainstitution QS:P195,somevalue,P3831,Q768717"
  },
  "earth": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/3d/1996._%D0%9A%D0%B0%D0%B4%D1%80_%D0%B8%D0%B7_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B0_%D0%97%D0%B5%D0%BC%D0%BB%D1%8F.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:1996._%D0%9A%D0%B0%D0%B4%D1%80_%D0%B8%D0%B7_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B0_%D0%97%D0%B5%D0%BC%D0%BB%D1%8F.jpg",
    "licenseName": "Public domain",
    "attribution": "Post of Ukraine / http://www.love-cinema.ru/publ/15-1-0-717"
  },
  "arsenal": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/7c/1929._%D0%A1%D0%B5%D0%BC%D0%B5%D0%BD_%D0%A1%D0%B2%D0%B0%D1%88%D0%B5%D0%BD%D0%BA%D0%BE_%D0%B2_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B5_%D0%90%D1%80%D1%81%D0%B5%D0%BD%D0%B0%D0%BB.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:1929._%D0%A1%D0%B5%D0%BC%D0%B5%D0%BD_%D0%A1%D0%B2%D0%B0%D1%88%D0%B5%D0%BD%D0%BA%D0%BE_%D0%B2_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B5_%D0%90%D1%80%D1%81%D0%B5%D0%BD%D0%B0%D0%BB.jpg",
    "licenseName": "Public domain",
    "attribution": "Оператор Даниил Демуцкий / http://www.russiancinema.ru/template.php?dept_id=3&amp;e_dept_id=2&amp;e_movie_id=283"
  },
  "strike": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Stachka.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Stachka.jpg",
    "licenseName": "Public domain",
    "attribution": "Sergueï Eisenstein / see above"
  },
  "mother": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b2/%D0%9F%D0%BB%D0%B0%D0%BA%D0%B0%D1%82_%D0%BA_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D1%83_%C2%AB%D0%9C%D0%B0%D1%82%D1%8C%C2%BB.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9F%D0%BB%D0%B0%D0%BA%D0%B0%D1%82_%D0%BA_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D1%83_%C2%AB%D0%9C%D0%B0%D1%82%D1%8C%C2%BB.jpg",
    "licenseName": "Public domain",
    "attribution": "Grigory Borisov / Российская государственная библиотека"
  },
  "the-end-of-st-petersburg": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/33/End_spb.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:End_spb.jpg",
    "licenseName": "Public domain",
    "attribution": "Vsevolod Pudovkin, Mikhail Doller, Nathan Zarkhi / Russian magazine Art of cinema photofiles"
  },
  "bed-and-sofa": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/28/Scene_from_Bed_and_Sofa.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Scene_from_Bed_and_Sofa.jpg",
    "licenseName": "Public domain",
    "attribution": "Mosfilm / Performing Arts Special Collections, UCLA Library Digital Collections, https://digital.library.ucla.edu/catalog/ark:/21198/zz00281t30"
  },
  "chapaev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/e4/%D0%A7%D0%B0%D0%BF%D0%B0%D0%B5%D0%B2_%D0%BA%D0%B0%D0%B4%D1%80_%D0%91%D0%B0%D0%B1%D0%BE%D1%87%D0%BA%D0%B8%D0%BD.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%A7%D0%B0%D0%BF%D0%B0%D0%B5%D0%B2_%D0%BA%D0%B0%D0%B4%D1%80_%D0%91%D0%B0%D0%B1%D0%BE%D1%87%D0%BA%D0%B8%D0%BD.jpg",
    "licenseName": "Public domain",
    "attribution": "Ленфильм / к/ф «Чапаев» 1934 года"
  },
  "jolly-fellows": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/36/%D0%92%D0%B5%D1%81%D0%B5%D0%BB%D1%8B%D0%B5_%D1%80%D0%B5%D0%B1%D1%8F%D1%82%D0%B0.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%B5%D1%81%D0%B5%D0%BB%D1%8B%D0%B5_%D1%80%D0%B5%D0%B1%D1%8F%D1%82%D0%B0.jpg",
    "licenseName": "Public domain",
    "attribution": "Mosfilm / Jolly Fellows"
  },
  "the-twelve-chairs": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/81/Gomiashvili_and_Filippov_1970.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Gomiashvili_and_Filippov_1970.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Главархив Москвы / https://www.mos.ru/news/item/20387073/"
  },
  "afonya": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Yevgeny_Leonov_on_Afonya.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Yevgeny_Leonov_on_Afonya.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Главархив Москвы / https://www.mos.ru/news/item/134907073/"
  },
  "an-ordinary-miracle": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/80/Yankovsky%2C_Zakharov%2C_Larionov.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Yankovsky,_Zakharov,_Larionov.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Igor Gnevashev / https://www.mos.ru/news/item/62905073/"
  },
  "that-same-munchausen": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Oleg_Yankovsky_1979.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Oleg_Yankovsky_1979.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Igor Gnevashev / https://www.mos.ru/news/item/62905073/"
  },
  "liberation": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/db/Bundesarchiv_Bild_183-L0508-0031%2C_Berlin%2C_Karl-Marx-Allee%2C_Kino_%22International%22.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Bundesarchiv_Bild_183-L0508-0031,_Berlin,_Karl-Marx-Allee,_Kino_%22International%22.jpg",
    "licenseName": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "attribution": "Hans-Joachim Spremberg / This image was provided to Wikimedia Commons by the German Federal Archive (Deutsches Bundesarchiv) as part of a cooperation project. The German Federal Archive guarantees an authentic representation only using the originals (negative and/or positive), resp. the digitalization of the originals as provided by the Digital Image Archive."
  },
  "the-lady-with-the-dog": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Crew_of_The_Lady_with_the_Dog_movie.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Crew_of_The_Lady_with_the_Dog_movie.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "М.А. Трахман (Главархив Москвы) / https://www.mos.ru/news/item/158835073/"
  },
  "october-ten-days-that-shook-the-world": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Movie_poster_October_%281927%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Movie_poster_October_(1927).jpg",
    "licenseName": "Public domain",
    "attribution": "Unknown authorUnknown author The original uploader was Animal-wiki at Russian Wikipedia.. неизвестен / Файл:Постер фильма «Октябрь» (СССР, 1927 г.).jpg (Original text : Transferred from ru.wikipedia to Commons. (Original text: http://www.postermandan.com/images/octoberR.jpg))"
  },
  "storm-over-asia": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f9/Still_frame_of_Inkijinoff_from_Storm_Over_Asia.png",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Still_frame_of_Inkijinoff_from_Storm_Over_Asia.png",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Mezhrabpomfilm / https://en.wikipedia.org/wiki/Storm_over_Asia_(1928_film)"
  },
  "aelita": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Aelita_1924_still_03.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Aelita_1924_still_03.jpg",
    "licenseName": "Public domain",
    "attribution": "Кинокомпания «Межрабпом-Русь». / [1]"
  },
  "stalker": {
    "url": "https://i.ytimg.com/vi/UPerb922QGM/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=UPerb922QGM",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "ivans-childhood": {
    "url": "https://i.ytimg.com/vi/SbJukagA0lg/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=SbJukagA0lg",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "the-mirror": {
    "url": "https://i.ytimg.com/vi/2ieiLy_HrHA/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=2ieiLy_HrHA",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "come-and-see": {
    "url": "https://i.ytimg.com/vi/zjIiApN6cfg/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=zjIiApN6cfg",
    "licenseName": "Official YouTube upload",
    "attribution": "Mosfilm (official YouTube)"
  },
  "the-ascent": {
    "url": "https://i.ytimg.com/vi/VteY61FDhc8/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=VteY61FDhc8",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "moscow-does-not-believe-in-tears": {
    "url": "https://i.ytimg.com/vi/X7GuhjGZ-xs/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=X7GuhjGZ-xs",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "the-diamond-arm": {
    "url": "https://i.ytimg.com/vi/M9cGHdVbNXI/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=M9cGHdVbNXI",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "the-snow-queen": {
    "url": "https://i.ytimg.com/vi/Qp8ZhJqzABs/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=Qp8ZhJqzABs",
    "licenseName": "Official YouTube upload",
    "attribution": "Мультики студии Союзмультфильм (official YouTube)"
  },
  "the-tale-of-tsar-saltan": {
    "url": "https://i.ytimg.com/vi/f0Sfwa9VqT8/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=f0Sfwa9VqT8",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "andrei-rublev": {
    "url": "https://i.ytimg.com/vi/je75FDjcUP4/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=je75FDjcUP4",
    "licenseName": "Official YouTube upload",
    "attribution": "Mosfilm (official YouTube)"
  },
  "ivan-the-terrible-part-i": {
    "url": "https://i.ytimg.com/vi/ZYOxxp_EVxc/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=ZYOxxp_EVxc",
    "licenseName": "Official YouTube upload",
    "attribution": "Mosfilm (official YouTube)"
  },
  "i-am-cuba": {
    "url": "https://i.ytimg.com/vi/Y3HpI898dwg/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=Y3HpI898dwg",
    "licenseName": "Official YouTube upload",
    "attribution": "Mosfilm (official YouTube)"
  },
  "white-sun-of-the-desert": {
    "url": "https://i.ytimg.com/vi/GqnqFhc9aho/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=GqnqFhc9aho",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "ivan-vasilievich-changes-profession": {
    "url": "https://i.ytimg.com/vi/TQ8onQu5QKY/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=TQ8onQu5QKY",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "gentlemen-of-fortune": {
    "url": "https://i.ytimg.com/vi/8tJPKSz6Gaw/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=8tJPKSz6Gaw",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "mimino": {
    "url": "https://i.ytimg.com/vi/GgFLr2bjUNM/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=GgFLr2bjUNM",
    "licenseName": "Official YouTube upload",
    "attribution": "Mosfilm (official YouTube)"
  },
  "autumn-marathon": {
    "url": "https://i.ytimg.com/vi/deEuVTAAzbg/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=deEuVTAAzbg",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "carnival-night": {
    "url": "https://i.ytimg.com/vi/fEntSqfPC0g/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=fEntSqfPC0g",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "tale-of-tales": {
    "url": "https://i.ytimg.com/vi/vTowzpTwv4s/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=vTowzpTwv4s",
    "licenseName": "Official YouTube upload",
    "attribution": "Мультики студии Союзмультфильм (official YouTube)"
  },
  "the-mystery-of-the-third-planet": {
    "url": "https://i.ytimg.com/vi/HZodexUkiDI/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=HZodexUkiDI",
    "licenseName": "Official YouTube upload",
    "attribution": "Мультики студии Союзмультфильм (official YouTube)"
  },
  "ivan-the-terrible-part-ii": {
    "url": "https://i.ytimg.com/vi/i5g-Ss9BDR4/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=i5g-Ss9BDR4",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "hussar-ballad": {
    "url": "https://i.ytimg.com/vi/929O4WzLRDg/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=929O4WzLRDg",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "wings": {
    "url": "https://i.ytimg.com/vi/lO6f6nO5HB4/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=lO6f6nO5HB4",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "welcome-or-no-trespassing": {
    "url": "https://i.ytimg.com/vi/e-r9XNmqQHk/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=e-r9XNmqQHk",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "fate-of-a-man": {
    "url": "https://i.ytimg.com/vi/ov7bKyahGL4/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=ov7bKyahGL4",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "the-dawns-here-are-quiet": {
    "url": "https://i.ytimg.com/vi/wk6TCpXjPFU/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=wk6TCpXjPFU",
    "licenseName": "Official YouTube upload",
    "attribution": "Киностудия Горького (official YouTube)"
  },
  "sadko": {
    "url": "https://i.ytimg.com/vi/zedi4fgeMeI/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=zedi4fgeMeI",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "kidnapping-caucasian-style": {
    "url": "https://i.ytimg.com/vi/0f1LxDfNpv0/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=0f1LxDfNpv0",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "walking-the-streets-of-moscow": {
    "url": "https://i.ytimg.com/vi/vbjs5zfxDMs/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=vbjs5zfxDMs",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "love-and-doves": {
    "url": "https://i.ytimg.com/vi/CLjLLHDUiiA/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=CLjLLHDUiiA",
    "licenseName": "Official YouTube upload",
    "attribution": "Mosfilm (official YouTube)"
  },
  "they-fought-for-their-country": {
    "url": "https://i.ytimg.com/vi/xfUlR_nuBb4/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=xfUlR_nuBb4",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "belorussian-station": {
    "url": "https://i.ytimg.com/vi/AafJinhS1fc/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=AafJinhS1fc",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "an-unfinished-piece-for-mechanical-piano": {
    "url": "https://i.ytimg.com/vi/0OXkvpVCZEA/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=0OXkvpVCZEA",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "a-slave-of-love": {
    "url": "https://i.ytimg.com/vi/majTxmCiw5k/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=majTxmCiw5k",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "oblomov": {
    "url": "https://i.ytimg.com/vi/Q1zIasC2Og8/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=Q1zIasC2Og8",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "at-home-among-strangers": {
    "url": "https://i.ytimg.com/vi/e0ECy37ayUw/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=e0ECy37ayUw",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "letter-never-sent": {
    "url": "https://i.ytimg.com/vi/qPScCOavuY8/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=qPScCOavuY8",
    "licenseName": "Official YouTube upload",
    "attribution": "Mosfilm (official YouTube)"
  },
  "little-vera": {
    "url": "https://i.ytimg.com/vi/E8MCiceJJdY/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=E8MCiceJJdY",
    "licenseName": "Official YouTube upload",
    "attribution": "Киностудия Горького (official YouTube)"
  },
  "assa": {
    "url": "https://i.ytimg.com/vi/1Plo-PLxVg4/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=1Plo-PLxVg4",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "morozko": {
    "url": "https://i.ytimg.com/vi/TESoWRfVPCc/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=TESoWRfVPCc",
    "licenseName": "Official YouTube upload",
    "attribution": "Киностудия Горького (official YouTube)"
  },
  "ruslan-and-lyudmila": {
    "url": "https://i.ytimg.com/vi/hXz4dKq0Cps/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=hXz4dKq0Cps",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "scarlet-sails": {
    "url": "https://i.ytimg.com/vi/5YzwW4hxrx4/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=5YzwW4hxrx4",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "nu-pogodi": {
    "url": "https://i.ytimg.com/vi/jlyzTjzseOk/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=jlyzTjzseOk",
    "licenseName": "Official YouTube upload",
    "attribution": "Мультики студии Союзмультфильм (official YouTube)"
  },
  "the-scarlet-flower": {
    "url": "https://i.ytimg.com/vi/1FtcZy6fow0/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=1FtcZy6fow0",
    "licenseName": "Official YouTube upload",
    "attribution": "Союзмультфильм (official YouTube)"
  },
  "the-bremen-town-musicians": {
    "url": "https://i.ytimg.com/vi/EZ70fF0htjQ/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=EZ70fF0htjQ",
    "licenseName": "Official YouTube upload",
    "attribution": "Союзмультфильм (official YouTube)"
  },
  "solaris": {
    "url": "https://i.ytimg.com/vi/Z8ZhQPaw4rE/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=Z8ZhQPaw4rE",
    "licenseName": "Official YouTube upload",
    "attribution": "Mosfilm (official YouTube)"
  },
  "ballad-of-a-soldier": {
    "url": "https://i.ytimg.com/vi/Vsnius8Ka_I/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=Vsnius8Ka_I",
    "licenseName": "Official YouTube upload",
    "attribution": "Mosfilm (official YouTube)"
  },
  "ilya-muromets": {
    "url": "https://i.ytimg.com/vi/pOhiBtmU-PE/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=pOhiBtmU-PE",
    "licenseName": "Official YouTube upload",
    "attribution": "Мосфильм - для детей (official YouTube)"
  },
  "viy": {
    "url": "https://i.ytimg.com/vi/Amh3uudVMBo/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=Amh3uudVMBo",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "siberiade": {
    "url": "https://i.ytimg.com/vi/6P5Nf7xzXS0/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=6P5Nf7xzXS0",
    "licenseName": "Official YouTube upload",
    "attribution": "Киноконцерн \"Мосфильм\" (official YouTube)"
  },
  "brief-encounters": {
    "url": "https://i.ytimg.com/vi/Qaj3RRFNP5c/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=Qaj3RRFNP5c",
    "licenseName": "Official YouTube upload",
    "attribution": "Odesa Film Studio (official YouTube)"
  },
  "heart-of-a-dog": {
    "url": "https://i.ytimg.com/vi/FeGuBXYLbug/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=FeGuBXYLbug",
    "licenseName": "Official YouTube upload",
    "attribution": "Channel Five / Lenfilm (official YouTube)"
  },
  "shadows-of-forgotten-ancestors": {
    "url": "https://i.ytimg.com/vi/1EpSSmcusUI/hq1.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=1EpSSmcusUI",
    "licenseName": "Official YouTube upload",
    "attribution": "Dovzhenko Centre (official YouTube)"
  },
  "repentance": {
    "url": "https://i.ytimg.com/vi/bIIb5wUzjdc/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=bIIb5wUzjdc",
    "licenseName": "Licensed distributor upload",
    "attribution": "RVISION (licensed distributor)"
  },
  "the-needle": {
    "url": "https://i.ytimg.com/vi/UFEMle60E-4/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=UFEMle60E-4",
    "licenseName": "Licensed upload",
    "attribution": "UNESCO Almaty (licensed)"
  },
  "twenty-days-without-war": {
    "url": "https://i.ytimg.com/vi/Xd8cptrLhm8/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=Xd8cptrLhm8",
    "licenseName": "Unverified source",
    "attribution": "Первый канал ЦТ СССР (unverified source)"
  },
  "king-lear": {
    "url": "https://i.ytimg.com/vi/BqS1V41MjFQ/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=BqS1V41MjFQ",
    "licenseName": "Unverified source",
    "attribution": "Кино Советской Эпохи (unverified source)"
  },
  "my-friend-ivan-lapshin": {
    "url": "https://i.ytimg.com/vi/SnS5xz_XniI/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=SnS5xz_XniI",
    "licenseName": "Unverified source",
    "attribution": "Кино Советской Эпохи (unverified source)"
  },
  "the-color-of-pomegranates": {
    "url": "https://i.ytimg.com/vi/9XN3vgj2za4/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=9XN3vgj2za4",
    "licenseName": "Unverified source",
    "attribution": "parajanovtv (unverified source)"
  },
  "planet-of-storms": {
    "url": "https://i.ytimg.com/vi/IC1J_ZprwJs/hqdefault.jpg",
    "descriptionUrl": "https://www.youtube.com/watch?v=IC1J_ZprwJs",
    "licenseName": "Unverified source",
    "attribution": "WonderLife (unverified source)"
  }
};

export const personImages: Record<string, ImageRecord> = {
  "akira-kurosawa": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/48/Akirakurosawa-onthesetof7samurai-1953-page88.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Akirakurosawa-onthesetof7samurai-1953-page88.jpg",
    "licenseName": "Public domain",
    "attribution": "映画の友 (Eiga no tomo) / Scan from the original work"
  },
  "yuri-solomin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/50/Vladimir_Putin_in_Lenkom_30_November_2011_10.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Vladimir_Putin_in_Lenkom_30_November_2011_10.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "premier.gov.ru / http://archive.premier.gov.ru/events/news/17273/photolents.html"
  },
  "eldar-ryazanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/89/Eldar_Ryazanov_1990s_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Eldar_Ryazanov_1990s_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Г. Ровенский / Главархив Москвы / https://www.mos.ru/news/item/97212073/"
  },
  "andrei-myagkov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/21/Andrey_Myagkov.jpeg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Andrey_Myagkov.jpeg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Пресс-служба Президента РФ / http://президент.рф/новости/19924 http://kremlin.ru/events/president/news/19924/photos/18238"
  },
  "barbara-brylska": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Barbara_Brylska.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Barbara_Brylska.JPG",
    "licenseName": "Public domain",
    "attribution": "Jerzy Kośnik / A Polish film magazine „Film” (weekly), May 21st 1978, the front cover. No copyright notice. / Polski tygodnik filmowy „Film”, nr 21 (1573) z 21 maja 1978, okładka."
  },
  "yuri-yakovlev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Yury_Yakovlev_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Yury_Yakovlev_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Russian Presidential Press and Information Office; crop by User:Pruneau / http://www.kremlin.ru/eng/sdocs/news.shtml?month=10&amp;day=&amp;year=2008&amp;Submit.x=7&amp;Submit.y=9&amp;prefix=&amp;value_from=&amp;value_to=&amp;date=&amp;stype=&amp;dayRequired=no&amp;day_enable=true#"
  },
  "vladimir-menshov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/08/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9C%D0%B5%D0%BD%D1%8C%D1%88%D0%BE%D0%B2_2018_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9C%D0%B5%D0%BD%D1%8C%D1%88%D0%BE%D0%B2_2018_(cropped).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Svklimkin / Own work"
  },
  "vera-alentova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Menshov_Alentova_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Menshov_Alentova_(cropped).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "irina-muravyova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/69/Maly_Theatre_foto_17_%D0%98%D1%80%D0%B8%D0%BD%D0%B0_%D0%9C%D1%83%D1%80%D0%B0%D0%B2%D1%8C%D1%91%D0%B2%D0%B0_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Maly_Theatre_foto_17_%D0%98%D1%80%D0%B8%D0%BD%D0%B0_%D0%9C%D1%83%D1%80%D0%B0%D0%B2%D1%8C%D1%91%D0%B2%D0%B0_(cropped).jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Zimin.V.G. / Own work"
  },
  "alisa-freindlich": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/69/Alisa_Freyndlich.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Alisa_Freyndlich.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Presidential Press and Information Office / http://www.kremlin.ru/articles/intevents4f.shtml"
  },
  "leonid-gaidai": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/a3/%D0%9B%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4_%D0%93%D0%B0%D0%B9%D0%B4%D0%B0%D0%B9_%281974%29_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9B%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4_%D0%93%D0%B0%D0%B9%D0%B4%D0%B0%D0%B9_(1974)_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Н. В. Гнисюк / Главархив Москвы / Учись, студент: как в советском кино появился Шурик"
  },
  "yuri-nikulin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/62/%D0%AE%D1%80%D0%B8%D0%B9_%D0%9D%D0%B8%D0%BA%D1%83%D0%BB%D0%B8%D0%BD1.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%AE%D1%80%D0%B8%D0%B9_%D0%9D%D0%B8%D0%BA%D1%83%D0%BB%D0%B8%D0%BD1.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Anastasiya Fedorenko / has been sent by email from author"
  },
  "andrei-mironov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/14/%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%9C%D0%B8%D1%80%D0%BE%D0%BD%D0%BE%D0%B2_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%9C%D0%B8%D1%80%D0%BE%D0%BD%D0%BE%D0%B2_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Театр сатиры / 95 лет с улыбкой. Как появился и чем живет сегодня Театр сатирыВечно юный и смешливый: каким Московский академический театр сатиры встретил столетие"
  },
  "anatoly-papanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Anatoli_Papanov_%281%29_cr.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Anatoli_Papanov_(1)_cr.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Игорь Верещагин / Own work"
  },
  "aleksandr-demyanenko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/58/%D0%90._%D0%A1._%D0%94%D0%B5%D0%BC%D1%8C%D1%8F%D0%BD%D0%B5%D0%BD%D0%BA%D0%BE..jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%90._%D0%A1._%D0%94%D0%B5%D0%BC%D1%8C%D1%8F%D0%BD%D0%B5%D0%BD%D0%BA%D0%BE..jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "PepperDew / Own work"
  },
  "georgy-vitsin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/8a/%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9_%D0%92%D0%B8%D1%86%D0%B8%D0%BD_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9_%D0%92%D0%B8%D1%86%D0%B8%D0%BD_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Александр Коньков / ТАСС / Георгий Вицин без прикрас (also: [1], [2])"
  },
  "yevgeny-morgunov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Morgunov_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Morgunov_(cropped).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "stanislav-lyubshin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/de/Lyubshin.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Lyubshin.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Alexey Yushenkov/Алексей Юшенков / Own work"
  },
  "yevgeny-leonov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/1c/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9_%D0%9B%D0%B5%D0%BE%D0%BD%D0%BE%D0%B2_%281979%29_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9_%D0%9B%D0%B5%D0%BE%D0%BD%D0%BE%D0%B2_(1979)_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Igor Gnevashev / Отдых и развлечения в июне: Главархив — о том, куда можно было пойти в Москве в 1983 году"
  },
  "levan-gabriadze": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/27/%D0%91%D0%B0%D1%88%D0%A4%D0%B5%D1%81%D1%82_%D0%93%D0%B0%D0%BB%D0%B0-%D0%BA%D0%BE%D0%BD%D1%86%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D1%8F_%D0%B8_%D0%A2%D0%B5%D0%B0%D1%82%D1%80%D0%93%D0%B0%D0%B1%D1%80%D0%B8%D0%B0%D0%B4%D0%B7%D0%B5_18.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%91%D0%B0%D1%88%D0%A4%D0%B5%D1%81%D1%82_%D0%93%D0%B0%D0%BB%D0%B0-%D0%BA%D0%BE%D0%BD%D1%86%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D1%8F_%D0%B8_%D0%A2%D0%B5%D0%B0%D1%82%D1%80%D0%93%D0%B0%D0%B1%D1%80%D0%B8%D0%B0%D0%B4%D0%B7%D0%B5_18.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Frolzart / Own work"
  },
  "sergei-parajanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/49/%D5%8D%D5%A5%D6%80%D5%A3%D5%A5%D5%B5_%D5%93%D5%A1%D6%80%D5%A1%D5%BB%D5%A1%D5%B6%D5%B8%D5%BE.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D5%8D%D5%A5%D6%80%D5%A3%D5%A5%D5%B5_%D5%93%D5%A1%D6%80%D5%A1%D5%BB%D5%A1%D5%B6%D5%B8%D5%BE.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Vahan Kochar / Own work"
  },
  "larisa-golubkina": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d8/%D0%9B%D0%B0%D1%80%D0%B8%D1%81%D0%B0_%D0%93%D0%BE%D0%BB%D1%83%D0%B1%D0%BA%D0%B8%D0%BD%D0%B0._%D0%A4%D0%BE%D1%82%D0%BE_%D0%90%D0%BD%D0%B0%D1%81%D1%82%D0%B0%D1%81%D0%B8%D0%B8_%D0%A4%D0%B5%D0%B4%D0%BE%D1%80%D0%B5%D0%BD%D0%BA%D0%BE.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9B%D0%B0%D1%80%D0%B8%D1%81%D0%B0_%D0%93%D0%BE%D0%BB%D1%83%D0%B1%D0%BA%D0%B8%D0%BD%D0%B0._%D0%A4%D0%BE%D1%82%D0%BE_%D0%90%D0%BD%D0%B0%D1%81%D1%82%D0%B0%D1%81%D0%B8%D0%B8_%D0%A4%D0%B5%D0%B4%D0%BE%D1%80%D0%B5%D0%BD%D0%BA%D0%BE.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Anastasiya Fedorenko / has been sent by email from author"
  },
  "oleg-vidov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/16/Oleg_Vidov_2013.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Oleg_Vidov_2013.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Glenn Francis / Own work"
  },
  "mikhail-kalatozov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/92/Mikhail_Kalatozov_PSE_Russia_2003.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Mikhail_Kalatozov_PSE_Russia_2003.jpg",
    "licenseName": "Public domain",
    "attribution": "Russian Post, Publishing and Trade Centre \"Marka\" (ИТЦ «Марка»). The designer of the envelope: O. Yudin. Scanned by Dmitry Ivanov / From a personal collection."
  },
  "tatiana-samoilova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/aa/Tatiana_Samoilova_%281968%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Tatiana_Samoilova_(1968).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Comet Photo AG (Zürich) / ETH-Bibliothek: E-Pics Bildarchiv online; http://doi.org/10.3932/ethz-a-000984259"
  },
  "aleksey-batalov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Alexey_Batalov_%28mos.ru%29_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Alexey_Batalov_(mos.ru)_(cropped).jpg",
    "licenseName": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attribution": "mos.ru / https://yakimanka.mos.ru/presscenter/news/detail/2729437.html"
  },
  "andrei-tarkovsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/30/Andrej_Tarkovskij_mug_shot_at_Latina_Refugee_Camp_1985_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Andrej_Tarkovskij_mug_shot_at_Latina_Refugee_Camp_1985_(cropped).jpg",
    "licenseName": "Public domain",
    "attribution": "Ministery of Interior of Italy / File:Scheda personale di registrazione di Andrei Tarkowski 2.jpg"
  },
  "donatas-banionis": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/17/Banionis.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Banionis.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Aviesvaikas / Own work"
  },
  "natalya-bondarchuk": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Natalya_Bondarchuk_2023.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Natalya_Bondarchuk_2023.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "duma.gov.ru / http://duma.gov.ru/multimedia/photo/86616/#slider-86616-86614"
  },
  "yuri-norstein": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Norstein2009-2.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Norstein2009-2.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Андрей Романенко / Own work"
  },
  "sergei-eisenstein": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/26/Sergei_Eisenstein_03.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Sergei_Eisenstein_03.jpg",
    "licenseName": "Public domain",
    "attribution": "Unknown authorUnknown author / Britannica"
  },
  "vladimir-barsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Barskiy-v01.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Barskiy-v01.jpg",
    "licenseName": "Public domain",
    "attribution": "Sergei Eisenstein / http://proekt-wms.narod.ru/zvezd/barsky-v.htm"
  },
  "grigori-aleksandrov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/64/Grigori_Aleksandrov_in_his_30s.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Grigori_Aleksandrov_in_his_30s.jpg",
    "licenseName": "Public domain",
    "attribution": "Grigory Aleksanodrov / https://24smi.org/public/media/resize/660x-/celebrity/2018/05/15/r8nes3qocvfp-grigorii-aleksandrov-v-molodosti.jpg"
  },
  "dziga-vertov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0e/David_Kaufman_%28Dziga_Vertov%29_1913.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:David_Kaufman_(Dziga_Vertov)_1913.jpg",
    "licenseName": "Public domain",
    "attribution": "Mikhail Kaufman / YouTube: https://www.youtube.com/watch?v=qdezIx9E1QE – View/save archived versions on archive.org"
  },
  "grigori-chukhrai": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/ca/%D0%93%D1%80%D0%B8%D0%B3%D0%BE%CC%81%D1%80%D0%B8%D0%B9_%D0%9D%D0%B0%D1%83%CC%81%D0%BC%D0%BE%D0%B2%D0%B8%D1%87_%D0%A7%D1%83%D1%85%D1%80%D0%B0%CC%81%D0%B9.webp",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%93%D1%80%D0%B8%D0%B3%D0%BE%CC%81%D1%80%D0%B8%D0%B9_%D0%9D%D0%B0%D1%83%CC%81%D0%BC%D0%BE%D0%B2%D0%B8%D1%87_%D0%A7%D1%83%D1%85%D1%80%D0%B0%CC%81%D0%B9.webp",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Unknown authorUnknown author / https://24smi.org/celebrity/43555-grigorii-chukhrai.html"
  },
  "vladimir-ivashov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/38/IvashovVS.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:IvashovVS.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "sergei-bondarchuk": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Sergei_Bondarchuk%2C_Sarajevo%2C_29._november_1969._Movie_premier_Battle_of_Neretva_by_Stevan_Kragujevic.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Sergei_Bondarchuk,_Sarajevo,_29._november_1969._Movie_premier_Battle_of_Neretva_by_Stevan_Kragujevic.JPG",
    "licenseName": "CC BY-SA 3.0 rs",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/rs/deed.en",
    "attribution": "Stevan Kragujević / Transferred from sr.wikipedia to Commons."
  },
  "lyudmila-savelyeva": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Ludmila_Saveljeva.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Ludmila_Saveljeva.jpg",
    "licenseName": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "attribution": "Evers, Joost / Anefo, [onbekend] / http://www.gahetna.nl/, Bestanddeelnummer 925-3573"
  },
  "vyacheslav-tikhonov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/7b/VTikhonov.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:VTikhonov.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "nikolai-grinko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/60/%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%93%D1%80%D0%B8%D0%BD%D1%8C%D0%BA%D0%BE_%281968%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%93%D1%80%D0%B8%D0%BD%D1%8C%D0%BA%D0%BE_(1968).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Главархив Москвы / https://www.mos.ru/news/item/68629073/"
  },
  "nikolay-burlyaev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%91%D1%83%D1%80%D0%BB%D1%8F%D0%B5%D0%B2_%2829-01-2026%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%91%D1%83%D1%80%D0%BB%D1%8F%D0%B5%D0%B2_(29-01-2026).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "duma.gov.ru / Круглый стол на тему «Государственная поддержка и пути развития отечественной кинематографии»"
  },
  "margarita-terekhova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Margarita_Terekhova_2003.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Margarita_Terekhova_2003.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Andrey Podoshian / Андрей Подошьян / Ticket#2021050610004614"
  },
  "alla-demidova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/80/Demidova%2C_Alla_-NF_20191207_fRF05.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Demidova,_Alla_-NF_20191207_fRF05.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Rodrigo Fernández / Own work"
  },
  "elem-klimov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Moscow_20200916_122131.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Moscow_20200916_122131.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Bogdanov-62 / Own work"
  },
  "boris-plotnikov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f7/%D0%91%D0%BE%D1%80%D0%B8%D1%81_%D0%9F%D0%BB%D0%BE%D1%82%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2_02.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%91%D0%BE%D1%80%D0%B8%D1%81_%D0%9F%D0%BB%D0%BE%D1%82%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2_02.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Zimin.V.G. / Own work"
  },
  "vladimir-gostyukhin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/00/Vladimir_Gostyukhin%2C_2017.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Vladimir_Gostyukhin,_2017.jpg",
    "licenseName": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attribution": "History Lab / Владимир Гостюхин о своем творчестве, кинематографе и Советском Союзе | History Lab. Интервью (frame grab, 2:52)"
  },
  "vladimir-andreyev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/6c/AndreevVA.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:AndreevVA.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "stanislav-govorukhin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/2c/%D0%A1%D1%82%D0%B0%D0%BD%D0%B8%D1%81%D0%BB%D0%B0%D0%B2_%D0%93%D0%BE%D0%B2%D0%BE%D1%80%D1%83%D1%85%D0%B8%D0%BD_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%A1%D1%82%D0%B0%D0%BD%D0%B8%D1%81%D0%BB%D0%B0%D0%B2_%D0%93%D0%BE%D0%B2%D0%BE%D1%80%D1%83%D1%85%D0%B8%D0%BD_(cropped).jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Евгения Давыдова / File:Станислав_Говорухин.jpg"
  },
  "nikolai-sergeyev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/17/Nikolai_Plotnikov_1939.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Nikolai_Plotnikov_1939.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "nikolai-cherkasov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/74/Nevski3.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Nevski3.jpg",
    "licenseName": "Public domain",
    "attribution": "Sergey Eisenstein / Russian Wikipedia, original description was/is here"
  },
  "nikolai-okhlopkov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/64/%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%9F%D0%B0%D0%B2%D0%BB%D0%BE%D0%B2%D0%B8%D1%87_%D0%9E%D1%85%D0%BB%D0%BE%D0%BF%D0%BA%D0%BE%D0%B2.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%9F%D0%B0%D0%B2%D0%BB%D0%BE%D0%B2%D0%B8%D1%87_%D0%9E%D1%85%D0%BB%D0%BE%D0%BF%D0%BA%D0%BE%D0%B2.jpg",
    "licenseName": "Public domain",
    "attribution": "Unknown authorUnknown author / Газета «Правда» 16 апреля 1949 годаhttps://goskatalog.ru/portal/#/collections?id=5993842"
  },
  "andrei-abrikosov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Andrei_Abrikosov_1935.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Andrei_Abrikosov_1935.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "lyudmila-tselikovskaya": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Lyudmila_Tselikovskaya_1948_2.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Lyudmila_Tselikovskaya_1948_2.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / https://www.kino-teatr.ru/kino/movie/sov/5220/foto/a4672/78495/"
  },
  "serafima-birman": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f0/%D0%95%D1%84%D1%80%D0%BE%D1%81%D0%B8%D0%BD%D1%8C%D1%8F_%D0%A1%D1%82%D0%B0%D1%80%D0%B8%D1%86%D0%BA%D0%B0%D1%8F.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%95%D1%84%D1%80%D0%BE%D1%81%D0%B8%D0%BD%D1%8C%D1%8F_%D0%A1%D1%82%D0%B0%D1%80%D0%B8%D1%86%D0%BA%D0%B0%D1%8F.jpg",
    "licenseName": "Public domain",
    "attribution": "киностудия ru:Мосфильм / russiancinema.ru"
  },
  "sergio-corrieri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Sergio_Corrieri.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Sergio_Corrieri.jpg",
    "licenseName": "Public domain",
    "attribution": "No machine-readable author provided. Yasinko assumed (based on copyright claims). / No machine-readable source provided. Own work assumed (based on copyright claims)."
  },
  "vladimir-motyl": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/70/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9C%D0%BE%D1%82%D1%8B%D0%BB%D1%8C_%281995-11-26%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9C%D0%BE%D1%82%D1%8B%D0%BB%D1%8C_(1995-11-26).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Главархив Москвы / https://www.mos.ru/news/item/145041073/"
  },
  "anatoly-kuznetsov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/80/%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D0%B8%D0%B9_%D0%9A%D1%83%D0%B7%D0%BD%D0%B5%D1%86%D0%BE%D0%B2_%281995-11-26%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%90%D0%BD%D0%B0%D1%82%D0%BE%D0%BB%D0%B8%D0%B9_%D0%9A%D1%83%D0%B7%D0%BD%D0%B5%D1%86%D0%BE%D0%B2_(1995-11-26).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Главархив Москвы / https://www.mos.ru/news/item/145041073/"
  },
  "pavel-luspekayev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/13/Customs_vereschagin.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Customs_vereschagin.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Kipelok / Own work"
  },
  "leonid-kuravlyov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/be/Kuravlev_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Kuravlev_(cropped).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Игорь Верещагин / Own work"
  },
  "georgiy-daneliya": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Danelia.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Danelia.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Alexey Yushenkov/Алексей Юшенков / Own work"
  },
  "vakhtang-kikabidze": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/65/Vakhtang_Kikabidze_2017-07-23_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Vakhtang_Kikabidze_2017-07-23_(cropped).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Okras / File:Vakhtang_Kikabidze_at_Laima_Rendez_Vous_Jurmala_2017.jpg"
  },
  "frunzik-mkrtchyan": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Mher_Mkrtchyan_2006_post_card_cropped.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Mher_Mkrtchyan_2006_post_card_cropped.jpg",
    "licenseName": "Public domain",
    "attribution": "Post Office of Armenia / http://www.armstamp.com/en/category/Stamps/2006.html"
  },
  "yelena-proklova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Elena_Proklova.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Elena_Proklova.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "old.oprf.ru / https://old.oprf.ru/ru/chambermembers/members/user/68?year=2006"
  },
  "oleg-basilashvili": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f5/%D0%9E%D0%BB%D0%B5%D0%B3_%D0%91%D0%B0%D1%81%D0%B8%D0%BB%D0%B0%D1%88%D0%B2%D0%B8%D0%BB%D0%B8_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9E%D0%BB%D0%B5%D0%B3_%D0%91%D0%B0%D1%81%D0%B8%D0%BB%D0%B0%D1%88%D0%B2%D0%B8%D0%BB%D0%B8_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Unknown authorUnknown author / Олег Басилашвили: «Свободу надо отстаивать»"
  },
  "natalya-gundareva": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/75/Natalya_Gundareva_1976.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Natalya_Gundareva_1976.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Igor Gnevashev / https://www.mos.ru/news/item/143137073/"
  },
  "lyudmila-gurchenko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c2/Gurchenko_1980s.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Gurchenko_1980s.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Igor Gnevashev / https://www.mos.ru/news/item/20387073/ (HQ)"
  },
  "igor-ilyinsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b1/%D0%92%D0%BE%D0%BB%D0%B3%D0%B0-%D0%92%D0%BE%D0%BB%D0%B3%D0%B0-%D0%BA%D0%B0%D0%B4%D1%80-2.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%BE%D0%BB%D0%B3%D0%B0-%D0%92%D0%BE%D0%BB%D0%B3%D0%B0-%D0%BA%D0%B0%D0%B4%D1%80-2.jpg",
    "licenseName": "Public domain",
    "attribution": "Киностудия «Мосфильм» / http://www.rosculture.ru/movies_list/search/show/?id=5912"
  },
  "larisa-kadochnikova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Larysa_Kadochnikova.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Larysa_Kadochnikova.jpg",
    "licenseName": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attribution": "News UTRAlina Naumets, Alina Kats, Ihor Korkodym / PULS NEWS AND PRESS-REVIEW IN ENGLISH. 23:00(+2GTM) 5 MARCH (Creative Commons – Attribution)"
  },
  "grigori-kozintsev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Grigori_Kozintsev_1958.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Grigori_Kozintsev_1958.jpg",
    "licenseName": "CC BY-SA 3.0 nl",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/nl/deed.en",
    "attribution": "Harry Pot for Anefo ]] / [1] Dutch National Archives, The Hague, Fotocollectie Algemeen Nederlands Persbureau (ANEFO), 1945-1989 bekijk toegang 2.24.01.04 Bestanddeelnummer 909-8978"
  },
  "innokenty-smoktunovsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/00/%D0%98%D0%BD%D0%BD%D0%BE%D0%BA%D0%B5%D0%BD%D1%82%D0%B8%D0%B9_%D0%A1%D0%BC%D0%BE%D0%BA%D1%82%D1%83%D0%BD%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%98%D0%BD%D0%BD%D0%BE%D0%BA%D0%B5%D0%BD%D1%82%D0%B8%D0%B9_%D0%A1%D0%BC%D0%BE%D0%BA%D1%82%D1%83%D0%BD%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Unknown authorUnknown author / Музей МХАТ / Феномен Смоктуновского. На Страстном бульваре откроется фотовыставка к 100-летию со дня рождения артиста"
  },
  "mikhail-nazvanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/15/Mikhail_Nazvanov_1947.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Mikhail_Nazvanov_1947.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / https://www.kino-teatr.ru/kino/movie/sov/6099/foto/a3013/143232/"
  },
  "anastasiya-vertinskaya": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Anastasiya_Vertinskaya_in_1964.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Anastasiya_Vertinskaya_in_1964.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Валентин Михайлович Мастюков, Главархив Москвы / https://www.mos.ru/news/item/91001073/"
  },
  "pavel-kadochnikov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/58/Kadochnikov.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Kadochnikov.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / https://www.kino-teatr.ru/kino/movie/sov/2020/foto/a1780/14584/"
  },
  "larisa-guzeyeva": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/53/Guzeeva-kremlin-3.jpeg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Guzeeva-kremlin-3.jpeg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Guzeeva-kremlin.jpeg: Presidential Press and Information Office derivative work: IgorEK II (talk) / Guzeeva-kremlin.jpeg"
  },
  "nikita-mikhalkov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/61/Mikhalkov_2022.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Mikhalkov_2022.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Пресс-служба Президента Российской Федерации / http://kremlin.ru/events/president/news/68650/photos/68228"
  },
  "valentin-gaft": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/68/Valentin_Gaft_%28mos.ru%2C_cropped%29_01.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Valentin_Gaft_(mos.ru,_cropped)_01.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "mos.ru / Government of Moscow Press centre"
  },
  "iya-savvina": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d2/%D0%98%D1%8F_%D0%A1%D0%B0%D0%B2%D0%B2%D0%B8%D0%BD%D0%B0_%281968%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%98%D1%8F_%D0%A1%D0%B0%D0%B2%D0%B2%D0%B8%D0%BD%D0%B0_(1968).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Главархив Москвы / https://www.mos.ru/news/item/20387073/"
  },
  "pavel-boriskin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/69/Pavel_Polunin.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Pavel_Polunin.jpg",
    "licenseName": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attribution": "Dmitry Rozhkov / Own work"
  },
  "zinaida-kiriyenko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/32/Zinaida_Kirienko_1.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Zinaida_Kirienko_1.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Dmitry Rozhkov / Own work"
  },
  "stanislav-rostotsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Stanislav_Rostotsky.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Stanislav_Rostotsky.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Boris Semenov / Boris Semenov archive at vk.com/semenovborisphoto"
  },
  "olga-ostroumova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/08/Olga_Ostroumova_2017.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Olga_Ostroumova_2017.jpg",
    "licenseName": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attribution": "VIC &amp; ADAMS / YouTube: https://www.youtube.com/watch?v=KEyEZLHYJm0 – View/save archived versions on archive.org"
  },
  "yelena-drapeko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/28/Yelena_Drapeko_2018-11-21.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Yelena_Drapeko_2018-11-21.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "duma.gov.ru / http://duma.gov.ru/multimedia/photo/28817/"
  },
  "sergei-stolyarov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Stoliarov.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Stoliarov.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "alla-larionova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/47/Alla_Larionova_in_%22Sadko%22_%281952%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Alla_Larionova_in_%22Sadko%22_(1952).jpg",
    "licenseName": "Public domain",
    "attribution": "Кинокстудия «Мосфильм» / https://www.kino-teatr.ru/kino/acter/w/ros/2434/foto/m6164/1465314/"
  },
  "boris-andreyev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Boris_Andreev_in_The_Fall_of_Berlin.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Boris_Andreev_in_The_Fall_of_Berlin.jpg",
    "licenseName": "Public domain",
    "attribution": "Мосфильм / YouTube: https://www.youtube.com/watch?v=8WfkPZ13HwM – View/save archived versions on archive.org"
  },
  "shukur-burkhanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Shukur_Burkhanov_-_Soviet_Life%2C_August_1983.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Shukur_Burkhanov_-_Soviet_Life,_August_1983.jpg",
    "licenseName": "Public domain",
    "attribution": "Published by the Embassy of the Union of Soviet Socialist Republics to the United States of America - uncredited photographer / losslessly cropped from File:Soviet Life, 1983-08, № 323.pdf"
  },
  "konstantin-yershov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f5/%D0%9D%D0%B0_%D1%81%D1%8A%D1%91%D0%BC%D0%BA%D0%B0%D1%85_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B0_%C2%AB%D0%A1%D1%82%D0%B5%D0%BF%D0%B0%D0%BD%D0%BE%D0%B2%D0%B0_%D0%BF%D0%B0%D0%BC%D1%8F%D1%82%D0%BA%D0%B0%C2%BB_%D1%80%D0%B5%D0%B6%D0%B8%D1%81%D1%81%D0%B5%D1%80_%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD_%D0%95%D1%80%D1%88%D0%BE%D0%B2_%D0%B8_%D0%B0%D0%BA%D1%82%D0%B5%D1%80_%D0%93%D0%B5%D0%BD%D0%BD%D0%B0%D0%B4%D0%B8%D0%B9_%D0%95%D0%B3%D0%BE%D1%80%D0%BE%D0%B2.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9D%D0%B0_%D1%81%D1%8A%D1%91%D0%BC%D0%BA%D0%B0%D1%85_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B0_%C2%AB%D0%A1%D1%82%D0%B5%D0%BF%D0%B0%D0%BD%D0%BE%D0%B2%D0%B0_%D0%BF%D0%B0%D0%BC%D1%8F%D1%82%D0%BA%D0%B0%C2%BB_%D1%80%D0%B5%D0%B6%D0%B8%D1%81%D1%81%D0%B5%D1%80_%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD_%D0%95%D1%80%D1%88%D0%BE%D0%B2_%D0%B8_%D0%B0%D0%BA%D1%82%D0%B5%D1%80_%D0%93%D0%B5%D0%BD%D0%BD%D0%B0%D0%B4%D0%B8%D0%B9_%D0%95%D0%B3%D0%BE%D1%80%D0%BE%D0%B2.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "фотограф Егорова Татьяна Сергеевна, photographer Tatyana Egorova / Own work. Ранее была опубликована с разрешения автора на ресурсе: http://www.kino-teatr.ru/teatr/acter/m/ros/1409/foto/447873/#foto"
  },
  "natalya-varley": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Natalya_Varley_03.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Natalya_Varley_03.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Dmitry Rozhkov / Own work"
  },
  "aleksandr-dovzhenko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f9/Alexander_Dovzhenko.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Alexander_Dovzhenko.jpg",
    "licenseName": "Public domain",
    "attribution": "Na / https://www.archives.gov.ua/Sections/Dovzhenko_2/CDAMLM/index.php?21"
  },
  "stepan-shkurat": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Stepan_Shkurat.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Stepan_Shkurat.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "semyon-svashenko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/5c/1929._%D0%A1%D0%B5%D0%BC%D0%B5%D0%BD_%D0%A1%D0%B2%D0%B0%D1%88%D0%B5%D0%BD%D0%BA%D0%BE_%D0%B2_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B5_%D0%90%D1%80%D1%81%D0%B5%D0%BD%D0%B0%D0%BB_%282%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:1929._%D0%A1%D0%B5%D0%BC%D0%B5%D0%BD_%D0%A1%D0%B2%D0%B0%D1%88%D0%B5%D0%BD%D0%BA%D0%BE_%D0%B2_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B5_%D0%90%D1%80%D1%81%D0%B5%D0%BD%D0%B0%D0%BB_(2).jpg",
    "licenseName": "Public domain",
    "attribution": "Оператор Даниил Демуцкий / http://www.russiancinema.ru/template.php?dept_id=3&amp;e_dept_id=2&amp;e_movie_id=283"
  },
  "yuliya-solntseva": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Solntseva_1924.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Solntseva_1924.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "amvrosii-buchma": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Amvrosy_Buchma.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Amvrosy_Buchma.jpg",
    "licenseName": "Public domain",
    "attribution": "Unknown authorUnknown author / https://www.archives.gov.ua/Sections/Buchma/Buchma.pdf"
  },
  "vasily-lanovoy": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/43/LanovoiV2001.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:LanovoiV2001.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "pavel-klushantsev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/fc/%D0%9F%D0%B0%D0%B2%D0%B5%D0%BB_%D0%9A%D0%BB%D1%83%D1%88%D0%B0%D0%BD%D1%86%D0%B5%D0%B2_1965.png",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9F%D0%B0%D0%B2%D0%B5%D0%BB_%D0%9A%D0%BB%D1%83%D1%88%D0%B0%D0%BD%D1%86%D0%B5%D0%B2_1965.png",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Michael Klushansev / Own work"
  },
  "georgi-zhzhonov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0a/ZhzhonovG.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:ZhzhonovG.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "vsevolod-pudovkin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/97/Vsevolod_Pudovkin_1929.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Vsevolod_Pudovkin_1929.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "vera-baranovskaya": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/3c/%D0%91%D0%B0%D1%80%D0%B0%D0%BD%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%D0%92%D0%B5%D1%80%D0%B0%D0%92%D1%81%D0%B5%D0%B2%D0%BE%D0%BB%D0%BE%D0%B4%D0%BE%D0%B2%D0%BD%D0%B0.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%91%D0%B0%D1%80%D0%B0%D0%BD%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F%D0%92%D0%B5%D1%80%D0%B0%D0%92%D1%81%D0%B5%D0%B2%D0%BE%D0%BB%D0%BE%D0%B4%D0%BE%D0%B2%D0%BD%D0%B0.jpg",
    "licenseName": "Public domain",
    "attribution": "Unknown authorUnknown author / http://www.kino-teatr.ru/kino/acter/w/empire/29154/forum/#1083502"
  },
  "nikolai-batalov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f1/Mat.Pavel_Vlasov_-_Batalov.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Mat.Pavel_Vlasov_-_Batalov.jpg",
    "licenseName": "Public domain",
    "attribution": "Vsevolod Pudovkin / Screenshot from soviet film Mat (1926) by Vsevolod Pudovkin"
  },
  "aleksandr-chistyakov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/64/APChistyakov1935.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:APChistyakov1935.jpg",
    "licenseName": "Public domain",
    "attribution": "Мосфильм / кадр из фильма «Лётчики»"
  },
  "valery-inkijinoff": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Actor_Val%C3%A9ry_Inkijinoff.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Actor_Val%C3%A9ry_Inkijinoff.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "The picture should be a still frame of the Russian production Storm over Asia (1928) / https://en.wikipedia.org/wiki/File:Val%C3%A9ry_Inkijinoff.jpg"
  },
  "yakov-protazanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d2/%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%AF._%D0%9F%D1%80%D0%BE%D1%82%D0%B0%D0%B7%D0%B0%D0%BD%D0%BE%D0%B2%D0%B0_%28%D0%97%D0%B0%D0%BB%D1%8C%D1%86%D0%B5%D1%80%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%AF._%D0%9F%D1%80%D0%BE%D1%82%D0%B0%D0%B7%D0%B0%D0%BD%D0%BE%D0%B2%D0%B0_(%D0%97%D0%B0%D0%BB%D1%8C%D1%86%D0%B5%D1%80).jpg",
    "licenseName": "Public domain",
    "attribution": "Семён Зельманович Зальцер (1898—1941) / Портрет Я. Протазанова"
  },
  "nikolai-tsereteli": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b5/Nikolai_Tseretelli_as_Lagutin.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Nikolai_Tseretelli_as_Lagutin.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "abram-room": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/16/Abram_Room_1940s.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Abram_Room_1940s.jpg",
    "licenseName": "Public domain",
    "attribution": "Unknown authorUnknown author / Ekran. revija za film in TV, leto III, marec- april 64. št. 16 - 17"
  },
  "lyudmila-semyonova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Liudmila_Semenova_1929.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Liudmila_Semenova_1929.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "vladimir-fogel": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Vladimir_Fogel.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Vladimir_Fogel.JPG",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Paul Munhoven / Own work"
  },
  "georgi-vasilyev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/77/%D0%91%D1%80%D0%B0%D1%82%D1%8C%D1%8F_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D1%8B_%D0%B8_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%A2%D0%BE%D0%BB%D1%81%D1%82%D0%BE%D0%B9%2C_1938_%D0%B3%D0%BE%D0%B4.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%91%D1%80%D0%B0%D1%82%D1%8C%D1%8F_%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2%D1%8B_%D0%B8_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%A2%D0%BE%D0%BB%D1%81%D1%82%D0%BE%D0%B9,_1938_%D0%B3%D0%BE%D0%B4.jpg",
    "licenseName": "Public domain",
    "attribution": "ТАСС / [1]. See also: [2]"
  },
  "boris-babochkin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/95/Babochkin_Chapayev1.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Babochkin_Chapayev1.jpg",
    "licenseName": "Public domain",
    "attribution": "en:Lenfilm / http://www.kp.ru/daily/23397/33678/"
  },
  "leonid-kmit": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/32/Leonid_Kmit.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Leonid_Kmit.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "varvara-myasnikova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/ee/VarvaraMiasnikova.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:VarvaraMiasnikova.JPG",
    "licenseName": "Public domain",
    "attribution": "Film screenshot / [1]"
  },
  "lyubov-orlova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Lyubov_Orlova_in_1945.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Lyubov_Orlova_in_1945.jpg",
    "licenseName": "Public domain",
    "attribution": "1945 / http://www.museum.ru/alb/image.asp?113564"
  },
  "kira-muratova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/50/Muratova.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Muratova.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "attribution": "Wikimedia Commons"
  },
  "vladimir-vysotsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/77/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%92%D1%8B%D1%81%D0%BE%D1%86%D0%BA%D0%B8%D0%B9_-_%D0%BF%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%92%D1%8B%D1%81%D0%BE%D1%86%D0%BA%D0%B8%D0%B9_-_%D0%BF%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Unknown authorUnknown author / Москва в памяти Владимира Высоцкого (immediate source) (HQ)"
  },
  "archil-gomiashvili": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/07/Gomiashvili_1970.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Gomiashvili_1970.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Главархив Москвы / https://www.mos.ru/news/item/20387073/"
  },
  "mikhail-pugovkin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/95/%D0%9F%D1%83%D0%B3%D0%BE%D0%B2%D0%BA%D0%B8%D0%BD_%D0%B2_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B5_%C2%AB%D0%94%D0%BE%D0%B1%D1%80%D0%BE%D0%B5_%D1%83%D1%82%D1%80%D0%BE%C2%BB.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9F%D1%83%D0%B3%D0%BE%D0%B2%D0%BA%D0%B8%D0%BD_%D0%B2_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B5_%C2%AB%D0%94%D0%BE%D0%B1%D1%80%D0%BE%D0%B5_%D1%83%D1%82%D1%80%D0%BE%C2%BB.jpg",
    "licenseName": "Public domain",
    "attribution": "Mosfilm / film screeenshots"
  },
  "galina-polskikh": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/e1/%D0%93%D0%B0%D0%BB%D0%B8%D0%BD%D0%B0_%D0%9F%D0%BE%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D1%85_%D0%BD%D0%B0_%D0%B2%D1%80%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B8_%D0%BF%D1%80%D0%B5%D0%BC%D0%B8%D0%B8_%D0%A1%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5_%D0%B3%D0%BE%D0%B4%D0%B0.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%93%D0%B0%D0%BB%D0%B8%D0%BD%D0%B0_%D0%9F%D0%BE%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D1%85_%D0%BD%D0%B0_%D0%B2%D1%80%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B8_%D0%BF%D1%80%D0%B5%D0%BC%D0%B8%D0%B8_%D0%A1%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5_%D0%B3%D0%BE%D0%B4%D0%B0.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Михаил Метцель / http://duma.gov.ru/media/photos/1254x705/rcfht44ZWyKyKGL6TnZFSAQBdU7WnHb4.jpg"
  },
  "aleksandr-mikhailov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/04/Mikhailov-1998.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Mikhailov-1998.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "nina-doroshina": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Vladimir_Zemlyanikin_and_Nina_Doroshina.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Vladimir_Zemlyanikin_and_Nina_Doroshina.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Unknown authorUnknown author / https://www.mos.ru/news/item/89429073/"
  },
  "mark-zakharov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/74/Mark_Zakharov_2011.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Mark_Zakharov_2011.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Совет Федерации / http://council.gov.ru/events/news/108239/ (HQ)"
  },
  "oleg-yankovsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/05/Oleg_Yankovsky2.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Oleg_Yankovsky2.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Tatyana Pankratova / https://bulldog-fill.com/kino.htm"
  },
  "inna-churikova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/78/Inna_Churikova_on_XXII_MIFF.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Inna_Churikova_on_XXII_MIFF.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Сергей Поминов / https://www.mos.ru/news/item/126886073/"
  },
  "leonid-bronevoy": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/85/Leonid_Bronevoy_%282008%29_03.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Leonid_Bronevoy_(2008)_03.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Пресс-служба Президента России / http://www.kremlin.ru/events/president/news/2543/photos"
  },
  "vladimir-bortko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/39/Vladimir_Bortko_2018.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Vladimir_Bortko_2018.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "duma.gov.ru / http://duma.gov.ru/multimedia/photo/29902/"
  },
  "vladimir-tolokonnikov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/a3/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%A2%D0%BE%D0%BB%D0%BE%D0%BA%D0%BE%D0%BD%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2_%D0%BD%D0%B0_%D1%81%D1%8A%D0%B5%D0%BC%D0%BA%D0%B0%D1%85_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B0_%C2%AB%D0%A5%D0%BE%D1%82%D1%82%D0%B0%D0%B1%D1%8B%D1%87%C2%BB_04.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%A2%D0%BE%D0%BB%D0%BE%D0%BA%D0%BE%D0%BD%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2_%D0%BD%D0%B0_%D1%81%D1%8A%D0%B5%D0%BC%D0%BA%D0%B0%D1%85_%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%B0_%C2%AB%D0%A5%D0%BE%D1%82%D1%82%D0%B0%D0%B1%D1%8B%D1%87%C2%BB_04.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Pure Engineer / Own work"
  },
  "roman-kartsev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Roman_Kartsev.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Roman_Kartsev.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Dmitry Rozhkov / Own work"
  },
  "yuri-ozerov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Stalingrad_Ozerov.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Stalingrad_Ozerov.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Photo from personal archive / http://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Stalingrad_Ozerov.jpg"
  },
  "vasily-shukshin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/14/%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D0%B9_%D0%A8%D1%83%D0%BA%D1%88%D0%B8%D0%BD_%281972%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D0%B8%D0%B9_%D0%A8%D1%83%D0%BA%D1%88%D0%B8%D0%BD_(1972).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Igor Gnevashev / https://www.mos.ru/news/item/20387073/"
  },
  "andrei-smirnov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/8d/%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%A1%D0%BC%D0%B8%D1%80%D0%BD%D0%BE%D0%B2_%2810-06-2023%29_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%A1%D0%BC%D0%B8%D1%80%D0%BD%D0%BE%D0%B2_(10-06-2023)_(cropped).jpg",
    "licenseName": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attribution": "Forbes / YouTube: Режиссер Андрей Смирнов о новом фильме «За нас с вами», цензуре и кино в современной России (Time: 2m10s) – View/save archived versions on archive.org"
  },
  "nina-urgant": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Nina_Urgant_1962.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Nina_Urgant_1962.jpg",
    "licenseName": "Public domain",
    "attribution": "Cameraphoto / https://megalodon.jp/2026-0401-0152-00/https://www.ebay.com:443/itm/316998640640"
  },
  "aleksei-petrenko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Alexey_Petrenko.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Alexey_Petrenko.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Игорь Верещагин / Own work"
  },
  "aleksandr-kalyagin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Kalyagin.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Kalyagin.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "oleg-tabakov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/92/OlegTabakov.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:OlegTabakov.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "andrei-konchalovsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/72/2023_Andrei_Konchalovsky_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:2023_Andrei_Konchalovsky_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "duma.gov.ru / http://duma.gov.ru/multimedia/photo/95923/"
  },
  "iosif-kheifits": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0b/%D0%98%D0%BE%D1%81%D0%B8%D1%84_%D0%A5%D0%B5%D0%B9%D1%84%D0%B8%D1%86_%281960%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%98%D0%BE%D1%81%D0%B8%D1%84_%D0%A5%D0%B5%D0%B9%D1%84%D0%B8%D1%86_(1960).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "М.А. Трахман (Главархив Москвы) / https://www.mos.ru/news/item/158835073/"
  },
  "oleg-dal": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Oleg_Dahl_in_Sovremennik_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Oleg_Dahl_in_Sovremennik_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "mos.ru / https://www.mos.ru/news/item/49173073/"
  },
  "tengiz-abuladze": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Tengiz_Abuladze_2024_stamp_of_Georgia.png",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Tengiz_Abuladze_2024_stamp_of_Georgia.png",
    "licenseName": "Public domain",
    "attribution": "B.Gagnidze (Georgia Post) / https://www.gpost.ge/shop/product?id=2862"
  },
  "natalya-negoda": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d7/%D0%9D%D0%B0%D1%82%D0%B0%D0%BB%D1%8C%D1%8F_%D0%9D%D0%B5%D0%B3%D0%BE%D0%B4%D0%B0_%D0%B2_%D0%95%D0%BB%D1%8C%D1%86%D0%B8%D0%BD-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%B5_7_%D0%BC%D0%B0%D1%80%D1%82%D0%B0_2020_%D0%B3%D0%BE%D0%B4%D0%B0.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9D%D0%B0%D1%82%D0%B0%D0%BB%D1%8C%D1%8F_%D0%9D%D0%B5%D0%B3%D0%BE%D0%B4%D0%B0_%D0%B2_%D0%95%D0%BB%D1%8C%D1%86%D0%B8%D0%BD-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%B5_7_%D0%BC%D0%B0%D1%80%D1%82%D0%B0_2020_%D0%B3%D0%BE%D0%B4%D0%B0.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Иван Абатуров / Own work"
  },
  "yuri-nazarov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/dd/Nazarov_Yuri_vlad_2.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Nazarov_Yuri_vlad_2.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Барканов Сергей Владимирович / Личная фототека"
  },
  "rashid-nugmanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/ee/RachidNougmanov.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:RachidNougmanov.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Y.Romanova / Own work"
  },
  "marina-smirnova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Marina_Smirnova_President_of_Young_Readers_Found.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Marina_Smirnova_President_of_Young_Readers_Found.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Michael Balaev / http://www.balaev.spb.ru/"
  },
  "pyotr-mamonov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Petr_Mamonov.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Petr_Mamonov.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Дмитрий Рузов / http://ruzovdmitry.livejournal.com/30329.html"
  },
  "sergei-solovyov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Sergey_Solovyov_2017.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Sergey_Solovyov_2017.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Svklimkin / Own work"
  },
  "tatyana-drubich": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/51/Tatyana_Drubich.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Tatyana_Drubich.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Zimin.V.G. / Own work"
  },
  "liya-akhedzhakova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/27/AhedzhakovaRozel.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:AhedzhakovaRozel.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Alexander Khanin / Own work"
  },
  "fyodor-khitruk": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0b/13134_6402f3fee6a73_%283%29.png",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:13134_6402f3fee6a73_(3).png",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Unknown authorUnknown author / https://page.lfl.ru/club/13134"
  },
  "nikolai-popov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/35/Nikolai_Popov%2C_1910s.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Nikolai_Popov,_1910s.jpg",
    "licenseName": "Public domain",
    "attribution": "Heinrich Riedel / http://ester.utlib.ee/record=b1706346~S1*est"
  },
  "leonid-utyosov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Leonid_Utesov_1934.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Leonid_Utesov_1934.jpg",
    "licenseName": "Public domain",
    "attribution": "w:Mosfilm / movie still"
  },
  "viktor-tsoi": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Victor_Tsoi_1986_cropped.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Victor_Tsoi_1986_cropped.jpg",
    "licenseName": "Public domain",
    "attribution": "Igor Moukhin / Victor_Tsoi_1986.jpg"
  },
  "sergei-bugaev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/cd/%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%91%D1%83%D0%B3%D0%B0%D0%B5%D0%B2_2026-03-28_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%91%D1%83%D0%B3%D0%B0%D0%B5%D0%B2_2026-03-28_(cropped).jpg",
    "licenseName": "Public domain",
    "attribution": "GAndy / Self-photographed"
  }
};
