// AUTO-GENERATED by scripts/fetch-images.ts — do not edit by hand.
// Freely-licensed Wikimedia Commons images for films and people.

export type ImageRecord = {
  url: string;
  descriptionUrl: string;
  licenseName: string;
  licenseUrl?: string;
  attribution: string;
};

export const filmImages: Record<string, ImageRecord> = {
  "the-cranes-are-flying": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/89/The_Cranes_Are_Flying_-_US_release_poster.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:The_Cranes_Are_Flying_-_US_release_poster.jpg",
    "licenseName": "Public domain",
    "attribution": "John J. Lomasney / Heritage Auctions"
  },
  "hedgehog-in-the-fog": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/1b/The_Soviet_Union_1988_CPA_5919_stamp_%28Hedgehog_in_the_Fog%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:The_Soviet_Union_1988_CPA_5919_stamp_(Hedgehog_in_the_Fog).jpg",
    "licenseName": "Public domain",
    "attribution": "USSR Post / Scanned 600 dpi by User Matsievsky from personal collection"
  },
  "battleship-potemkin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Battleship_Potemkin-Ship_portrait.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Battleship_Potemkin-Ship_portrait.jpg",
    "licenseName": "Public domain",
    "attribution": "SM Eisenstein / [1]"
  },
  "man-with-a-movie-camera": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Man_with_a_movie_camera_1929_2.png",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Man_with_a_movie_camera_1929_2.png",
    "licenseName": "Public domain",
    "attribution": "Dziga Vertov / http://anthologyfilmarchives.org/collections/reference-library/stills/683"
  },
  "war-and-peace": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c1/War_and_Peace_%281967%2C_Russia%29_movie_script.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:War_and_Peace_(1967,_Russia)_movie_script.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "shakko / Own work"
  },
  "dersu-uzala": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/48/Dersuuzala.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Dersuuzala.jpg",
    "licenseName": "Public domain",
    "attribution": "Vladimir Arsenyev / Владимир Клавдиевич Арсеньев. Собрание сочинений в 6 томах. Том I. / Под ред. ОИАК. — Владивосток, Альманах «Рубеж», 2007. — 704 с."
  },
  "the-irony-of-fate": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/1f/File_by_Alexander_Baranov_-_%D0%A1_%D0%9D%D0%BE%D0%B2%D1%8B%D0%BC_%D0%B3%D0%BE%D0%B4%D0%BE%D0%BC%21_%2811677507426%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:File_by_Alexander_Baranov_-_%D0%A1_%D0%9D%D0%BE%D0%B2%D1%8B%D0%BC_%D0%B3%D0%BE%D0%B4%D0%BE%D0%BC!_(11677507426).jpg",
    "licenseName": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "attribution": "Alexander Baranov from Montpellier, France / С Новым годом!"
  },
  "office-romance": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/12/Office_Romance_crew_05.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Office_Romance_crew_05.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "mos.ru / https://www.mos.ru/news/item/72911073/"
  },
  "operation-y-and-shuriks-other-adventures": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/24/Arkhangelskoye_Vadim_Zadorozhnys_Vehicle_Museum_S-3A_IMG_9619_2150.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Arkhangelskoye_Vadim_Zadorozhnys_Vehicle_Museum_S-3A_IMG_9619_2150.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Alexxx1979 / Own work"
  },
  "kin-dza-dza": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Pepelac2010.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Pepelac2010.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Pycckue / Own work"
  },
  "the-snow-queen": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/1b/2005._Stamp_of_Belarus_0614.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:2005._Stamp_of_Belarus_0614.jpg",
    "licenseName": "Public domain",
    "attribution": "post of Belarus / http://belpost.by/stamps/catalog-by-date/2005/"
  }
};

export const personImages: Record<string, ImageRecord> = {
  "akira-kurosawa": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/48/Akirakurosawa-onthesetof7samurai-1953-page88.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Akirakurosawa-onthesetof7samurai-1953-page88.jpg",
    "licenseName": "Public domain",
    "attribution": "映画の友 (Eiga no tomo) / Scan from the original work"
  },
  "yuri-solomin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/50/Vladimir_Putin_in_Lenkom_30_November_2011_10.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Vladimir_Putin_in_Lenkom_30_November_2011_10.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "premier.gov.ru / http://archive.premier.gov.ru/events/news/17273/photolents.html"
  },
  "eldar-ryazanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/89/Eldar_Ryazanov_1990s_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Eldar_Ryazanov_1990s_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Г. Ровенский / Главархив Москвы / https://www.mos.ru/news/item/97212073/"
  },
  "andrei-myagkov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/21/Andrey_Myagkov.jpeg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Andrey_Myagkov.jpeg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Пресс-служба Президента РФ / http://президент.рф/новости/19924 http://kremlin.ru/events/president/news/19924/photos/18238"
  },
  "barbara-brylska": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Barbara_Brylska.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Barbara_Brylska.JPG",
    "licenseName": "Public domain",
    "attribution": "Jerzy Kośnik / A Polish film magazine „Film” (weekly), May 21st 1978, the front cover. No copyright notice. / Polski tygodnik filmowy „Film”, nr 21 (1573) z 21 maja 1978, okładka."
  },
  "yury-yakovlev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Yury_Yakovlev_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Yury_Yakovlev_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Russian Presidential Press and Information Office; crop by User:Pruneau / http://www.kremlin.ru/eng/sdocs/news.shtml?month=10&amp;day=&amp;year=2008&amp;Submit.x=7&amp;Submit.y=9&amp;prefix=&amp;value_from=&amp;value_to=&amp;date=&amp;stype=&amp;dayRequired=no&amp;day_enable=true#"
  },
  "vladimir-menshov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/08/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9C%D0%B5%D0%BD%D1%8C%D1%88%D0%BE%D0%B2_2018_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%9C%D0%B5%D0%BD%D1%8C%D1%88%D0%BE%D0%B2_2018_(cropped).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Svklimkin / Own work"
  },
  "vera-alentova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Menshov_Alentova_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Menshov_Alentova_(cropped).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "irina-muravyova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/69/Maly_Theatre_foto_17_%D0%98%D1%80%D0%B8%D0%BD%D0%B0_%D0%9C%D1%83%D1%80%D0%B0%D0%B2%D1%8C%D1%91%D0%B2%D0%B0_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Maly_Theatre_foto_17_%D0%98%D1%80%D0%B8%D0%BD%D0%B0_%D0%9C%D1%83%D1%80%D0%B0%D0%B2%D1%8C%D1%91%D0%B2%D0%B0_(cropped).jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Zimin.V.G. / Own work"
  },
  "alisa-freindlich": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/69/Alisa_Freyndlich.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Alisa_Freyndlich.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Presidential Press and Information Office / http://www.kremlin.ru/articles/intevents4f.shtml"
  },
  "leonid-gaidai": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/a3/%D0%9B%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4_%D0%93%D0%B0%D0%B9%D0%B4%D0%B0%D0%B9_%281974%29_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9B%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4_%D0%93%D0%B0%D0%B9%D0%B4%D0%B0%D0%B9_(1974)_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Н. В. Гнисюк / Главархив Москвы / Учись, студент: как в советском кино появился Шурик"
  },
  "yuri-nikulin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/62/%D0%AE%D1%80%D0%B8%D0%B9_%D0%9D%D0%B8%D0%BA%D1%83%D0%BB%D0%B8%D0%BD1.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%AE%D1%80%D0%B8%D0%B9_%D0%9D%D0%B8%D0%BA%D1%83%D0%BB%D0%B8%D0%BD1.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Anastasiya Fedorenko / has been sent by email from author"
  },
  "andrei-mironov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/14/%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%9C%D0%B8%D1%80%D0%BE%D0%BD%D0%BE%D0%B2_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B9_%D0%9C%D0%B8%D1%80%D0%BE%D0%BD%D0%BE%D0%B2_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Театр сатиры / 95 лет с улыбкой. Как появился и чем живет сегодня Театр сатирыВечно юный и смешливый: каким Московский академический театр сатиры встретил столетие"
  },
  "anatoli-papanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Anatoli_Papanov_%281%29_cr.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Anatoli_Papanov_(1)_cr.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Игорь Верещагин / Own work"
  },
  "aleksandr-demyanenko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/5/58/%D0%90._%D0%A1._%D0%94%D0%B5%D0%BC%D1%8C%D1%8F%D0%BD%D0%B5%D0%BD%D0%BA%D0%BE..jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%90._%D0%A1._%D0%94%D0%B5%D0%BC%D1%8C%D1%8F%D0%BD%D0%B5%D0%BD%D0%BA%D0%BE..jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "PepperDew / Own work"
  },
  "georgy-vitsin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/8a/%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9_%D0%92%D0%B8%D1%86%D0%B8%D0%BD_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9_%D0%92%D0%B8%D1%86%D0%B8%D0%BD_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Александр Коньков / ТАСС / Георгий Вицин без прикрас (also: [1], [2])"
  },
  "yevgeny-morgunov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Morgunov_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Morgunov_(cropped).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "georgi-daneliya": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Danelia.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Danelia.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Alexey Yushenkov/Алексей Юшенков / Own work"
  },
  "stanislav-lyubshin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/de/Lyubshin.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Lyubshin.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Alexey Yushenkov/Алексей Юшенков / Own work"
  },
  "yevgeny-leonov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/1c/%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9_%D0%9B%D0%B5%D0%BE%D0%BD%D0%BE%D0%B2_%281979%29_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9_%D0%9B%D0%B5%D0%BE%D0%BD%D0%BE%D0%B2_(1979)_(cropped).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Igor Gnevashev / Отдых и развлечения в июне: Главархив — о том, куда можно было пойти в Москве в 1983 году"
  },
  "levan-gabriadze": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/27/%D0%91%D0%B0%D1%88%D0%A4%D0%B5%D1%81%D1%82_%D0%93%D0%B0%D0%BB%D0%B0-%D0%BA%D0%BE%D0%BD%D1%86%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D1%8F_%D0%B8_%D0%A2%D0%B5%D0%B0%D1%82%D1%80%D0%93%D0%B0%D0%B1%D1%80%D0%B8%D0%B0%D0%B4%D0%B7%D0%B5_18.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%91%D0%B0%D1%88%D0%A4%D0%B5%D1%81%D1%82_%D0%93%D0%B0%D0%BB%D0%B0-%D0%BA%D0%BE%D0%BD%D1%86%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D1%8F_%D0%B8_%D0%A2%D0%B5%D0%B0%D1%82%D1%80%D0%93%D0%B0%D0%B1%D1%80%D0%B8%D0%B0%D0%B4%D0%B7%D0%B5_18.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Frolzart / Own work"
  },
  "sergei-parajanov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/49/%D5%8D%D5%A5%D6%80%D5%A3%D5%A5%D5%B5_%D5%93%D5%A1%D6%80%D5%A1%D5%BB%D5%A1%D5%B6%D5%B8%D5%BE.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D5%8D%D5%A5%D6%80%D5%A3%D5%A5%D5%B5_%D5%93%D5%A1%D6%80%D5%A1%D5%BB%D5%A1%D5%B6%D5%B8%D5%BE.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Vahan Kochar / Own work"
  },
  "aleksandr-ptushko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Aleksandr_Ptushko_2025_postal_cover_of_Russia_cr.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Aleksandr_Ptushko_2025_postal_cover_of_Russia_cr.jpg",
    "licenseName": "Public domain",
    "attribution": "N. Karpova / [1]"
  },
  "larisa-golubkina": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d8/%D0%9B%D0%B0%D1%80%D0%B8%D1%81%D0%B0_%D0%93%D0%BE%D0%BB%D1%83%D0%B1%D0%BA%D0%B8%D0%BD%D0%B0._%D0%A4%D0%BE%D1%82%D0%BE_%D0%90%D0%BD%D0%B0%D1%81%D1%82%D0%B0%D1%81%D0%B8%D0%B8_%D0%A4%D0%B5%D0%B4%D0%BE%D1%80%D0%B5%D0%BD%D0%BA%D0%BE.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9B%D0%B0%D1%80%D0%B8%D1%81%D0%B0_%D0%93%D0%BE%D0%BB%D1%83%D0%B1%D0%BA%D0%B8%D0%BD%D0%B0._%D0%A4%D0%BE%D1%82%D0%BE_%D0%90%D0%BD%D0%B0%D1%81%D1%82%D0%B0%D1%81%D0%B8%D0%B8_%D0%A4%D0%B5%D0%B4%D0%BE%D1%80%D0%B5%D0%BD%D0%BA%D0%BE.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Anastasiya Fedorenko / has been sent by email from author"
  },
  "oleg-vidov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/16/Oleg_Vidov_2013.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Oleg_Vidov_2013.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Glenn Francis / Own work"
  },
  "mikhail-kalatozov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/92/Mikhail_Kalatozov_PSE_Russia_2003.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Mikhail_Kalatozov_PSE_Russia_2003.jpg",
    "licenseName": "Public domain",
    "attribution": "Russian Post, Publishing and Trade Centre \"Marka\" (ИТЦ «Марка»). The designer of the envelope: O. Yudin. Scanned by Dmitry Ivanov / From a personal collection."
  },
  "tatiana-samoilova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/aa/Tatiana_Samoilova_%281968%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Tatiana_Samoilova_(1968).jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Comet Photo AG (Zürich) / ETH-Bibliothek: E-Pics Bildarchiv online; http://doi.org/10.3932/ethz-a-000984259"
  },
  "aleksey-batalov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Alexey_Batalov_%28mos.ru%29_%28cropped%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Alexey_Batalov_(mos.ru)_(cropped).jpg",
    "licenseName": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attribution": "mos.ru / https://yakimanka.mos.ru/presscenter/news/detail/2729437.html"
  },
  "andrei-tarkovsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Andrei_tarkovsky_stamp_russia_2007.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Andrei_tarkovsky_stamp_russia_2007.jpg",
    "licenseName": "Public domain",
    "attribution": "Unknown authorUnknown author / Personal collection"
  },
  "donatas-banionis": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/17/Banionis.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Banionis.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Aviesvaikas / Own work"
  },
  "natalya-bondarchuk": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Natalya_Bondarchuk_2023.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Natalya_Bondarchuk_2023.jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "duma.gov.ru / http://duma.gov.ru/multimedia/photo/86616/#slider-86616-86614"
  },
  "yuri-norstein": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/4/4f/Norstein2009-2.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Norstein2009-2.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Андрей Романенко / Own work"
  },
  "sergei-eisenstein": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/2/26/Sergei_Eisenstein_03.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Sergei_Eisenstein_03.jpg",
    "licenseName": "Public domain",
    "attribution": "Unknown authorUnknown author / Britannica"
  },
  "vladimir-barsky": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c9/Barskiy-v01.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Barskiy-v01.jpg",
    "licenseName": "Public domain",
    "attribution": "Sergei Eisenstein / http://proekt-wms.narod.ru/zvezd/barsky-v.htm"
  },
  "grigori-aleksandrov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/64/Grigori_Aleksandrov_in_his_30s.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Grigori_Aleksandrov_in_his_30s.jpg",
    "licenseName": "Public domain",
    "attribution": "Grigory Aleksanodrov / https://24smi.org/public/media/resize/660x-/celebrity/2018/05/15/r8nes3qocvfp-grigorii-aleksandrov-v-molodosti.jpg"
  },
  "dziga-vertov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0e/David_Kaufman_%28Dziga_Vertov%29_1913.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:David_Kaufman_(Dziga_Vertov)_1913.jpg",
    "licenseName": "Public domain",
    "attribution": "Mikhail Kaufman / YouTube: https://www.youtube.com/watch?v=qdezIx9E1QE – View/save archived versions on archive.org"
  },
  "grigori-chukhrai": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/ca/%D0%93%D1%80%D0%B8%D0%B3%D0%BE%CC%81%D1%80%D0%B8%D0%B9_%D0%9D%D0%B0%D1%83%CC%81%D0%BC%D0%BE%D0%B2%D0%B8%D1%87_%D0%A7%D1%83%D1%85%D1%80%D0%B0%CC%81%D0%B9.webp",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%93%D1%80%D0%B8%D0%B3%D0%BE%CC%81%D1%80%D0%B8%D0%B9_%D0%9D%D0%B0%D1%83%CC%81%D0%BC%D0%BE%D0%B2%D0%B8%D1%87_%D0%A7%D1%83%D1%85%D1%80%D0%B0%CC%81%D0%B9.webp",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Unknown authorUnknown author / https://24smi.org/celebrity/43555-grigorii-chukhrai.html"
  },
  "vladimir-ivashov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/38/IvashovVS.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:IvashovVS.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "sergei-bondarchuk": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Sergei_Bondarchuk%2C_Sarajevo%2C_29._november_1969._Movie_premier_Battle_of_Neretva_by_Stevan_Kragujevic.JPG",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Sergei_Bondarchuk,_Sarajevo,_29._november_1969._Movie_premier_Battle_of_Neretva_by_Stevan_Kragujevic.JPG",
    "licenseName": "CC BY-SA 3.0 rs",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/rs/deed.en",
    "attribution": "Stevan Kragujević / Transferred from sr.wikipedia to Commons."
  },
  "lyudmila-savelyeva": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Ludmila_Saveljeva.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Ludmila_Saveljeva.jpg",
    "licenseName": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "attribution": "Evers, Joost / Anefo, [onbekend] / http://www.gahetna.nl/, Bestanddeelnummer 925-3573"
  },
  "vyacheslav-tikhonov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/7b/VTikhonov.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:VTikhonov.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Leo Medvedev/Лев Леонидович Медведев / Leo Medvedev’s Archive"
  },
  "nikolai-grinko": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/60/%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%93%D1%80%D0%B8%D0%BD%D1%8C%D0%BA%D0%BE_%281968%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%93%D1%80%D0%B8%D0%BD%D1%8C%D0%BA%D0%BE_(1968).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "Главархив Москвы / https://www.mos.ru/news/item/68629073/"
  },
  "nikolay-burlyaev": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%91%D1%83%D1%80%D0%BB%D1%8F%D0%B5%D0%B2_%2829-01-2026%29.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9_%D0%91%D1%83%D1%80%D0%BB%D1%8F%D0%B5%D0%B2_(29-01-2026).jpg",
    "licenseName": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "attribution": "duma.gov.ru / Круглый стол на тему «Государственная поддержка и пути развития отечественной кинематографии»"
  },
  "margarita-terekhova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Margarita_Terekhova_2003.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Margarita_Terekhova_2003.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Andrey Podoshian / Андрей Подошьян / Ticket#2021050610004614"
  },
  "alla-demidova": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/80/Demidova%2C_Alla_-NF_20191207_fRF05.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Demidova,_Alla_-NF_20191207_fRF05.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Rodrigo Fernández / Own work"
  },
  "elem-klimov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Moscow_20200916_122131.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Moscow_20200916_122131.jpg",
    "licenseName": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "attribution": "Bogdanov-62 / Own work"
  },
  "boris-plotnikov": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/f/f7/%D0%91%D0%BE%D1%80%D0%B8%D1%81_%D0%9F%D0%BB%D0%BE%D1%82%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2_02.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:%D0%91%D0%BE%D1%80%D0%B8%D1%81_%D0%9F%D0%BB%D0%BE%D1%82%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2_02.jpg",
    "licenseName": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "attribution": "Zimin.V.G. / Own work"
  },
  "vladimir-gostyukhin": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/00/Vladimir_Gostyukhin%2C_2017.jpg",
    "descriptionUrl": "https://commons.wikimedia.org/wiki/File:Vladimir_Gostyukhin,_2017.jpg",
    "licenseName": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "attribution": "History Lab / Владимир Гостюхин о своем творчестве, кинематографе и Советском Союзе | History Lab. Интервью (frame grab, 2:52)"
  }
};
