// AUTO-GENERATED by scripts/curate-region-links.ts — do not edit by hand.
// Verified US/international-available official uploads for films whose primary
// YouTube link is geo-blocked in the US, used for viewers outside Europe.

export type RegionLink = { url: string; sourceType: string; platform: string; label: string };

export const regionWatchLinks: Record<string, RegionLink> = {
  "the-cranes-are-flying": {
    "url": "https://www.youtube.com/watch?v=2rINnJat-5k",
    "platform": "YouTube",
    "sourceType": "OFFICIAL",
    "label": "Mosfilm"
  },
  "battleship-potemkin": {
    "url": "https://www.youtube.com/watch?v=a_bkBbrdyyw",
    "platform": "YouTube",
    "sourceType": "OFFICIAL",
    "label": "Mosfilm"
  },
  "war-and-peace": {
    "url": "https://www.youtube.com/watch?v=bIij-KQ0jYU",
    "platform": "YouTube",
    "sourceType": "OFFICIAL",
    "label": "Mosfilm"
  },
  "the-ascent": {
    "url": "https://www.youtube.com/watch?v=v21lQ449T3Y",
    "platform": "YouTube",
    "sourceType": "OFFICIAL",
    "label": "Mosfilm"
  },
  "dersu-uzala": {
    "url": "https://www.youtube.com/watch?v=sFaL03SKEzE",
    "platform": "YouTube",
    "sourceType": "OFFICIAL",
    "label": "Mosfilm"
  },
  "alexander-nevsky": {
    "url": "https://www.youtube.com/watch?v=Gq4PaJfod4w",
    "platform": "YouTube",
    "sourceType": "OFFICIAL",
    "label": "Mosfilm"
  },
  "i-am-cuba": {
    "url": "https://www.youtube.com/watch?v=INM-8BJtp7s",
    "platform": "YouTube",
    "sourceType": "UNVERIFIED",
    "label": "Alternate upload (unverified)"
  },
  "ivan-the-terrible-part-ii": {
    "url": "https://www.youtube.com/watch?v=vnNgoS8VsoQ",
    "platform": "YouTube",
    "sourceType": "OFFICIAL",
    "label": "Mosfilm"
  },
  "welcome-or-no-trespassing": {
    "url": "https://www.youtube.com/watch?v=X-4LQzazwUs",
    "platform": "YouTube",
    "sourceType": "OFFICIAL",
    "label": "Mosfilm"
  }
};
