// AUTO-GENERATED by scripts/find-watch-links.ts — do not edit by hand.
// Concrete free/legal watch URLs per film, with honest trust levels.

export type WatchLink = {
  url: string;
  sourceType: string;
  label: string;
  platform: string;
  rightsNote: string;
};

export const watchLinks: Record<string, WatchLink> = {
  "the-cranes-are-flying": {
    "url": "https://www.youtube.com/watch?v=2OccZQmxKac",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "solaris": {
    "url": "https://www.youtube.com/watch?v=Z8ZhQPaw4rE",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "hedgehog-in-the-fog": {
    "url": "https://www.youtube.com/watch?v=HPTkvoQZYlg",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "battleship-potemkin": {
    "url": "https://www.youtube.com/watch?v=GmUef84ybXk",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "man-with-a-movie-camera": {
    "url": "https://www.youtube.com/watch?v=U1bgnBLqMyg",
    "platform": "YouTube",
    "label": "kinoglaz",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "ballad-of-a-soldier": {
    "url": "https://www.youtube.com/watch?v=Vsnius8Ka_I",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "war-and-peace": {
    "url": "https://www.youtube.com/watch?v=V-SAh4jdssA",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "stalker": {
    "url": "https://www.youtube.com/watch?v=UPerb922QGM",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "ivans-childhood": {
    "url": "https://www.youtube.com/watch?v=SbJukagA0lg",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-mirror": {
    "url": "https://www.youtube.com/watch?v=2ieiLy_HrHA",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "come-and-see": {
    "url": "https://www.youtube.com/watch?v=zjIiApN6cfg",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-ascent": {
    "url": "https://www.youtube.com/watch?v=VteY61FDhc8",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "dersu-uzala": {
    "url": "https://www.youtube.com/watch?v=bp2ihvch45k",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-irony-of-fate": {
    "url": "https://www.youtube.com/watch?v=L5GnqepBJkE",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "moscow-does-not-believe-in-tears": {
    "url": "https://www.youtube.com/watch?v=X7GuhjGZ-xs",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "office-romance": {
    "url": "https://www.youtube.com/watch?v=hR-1QGMK75c",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-diamond-arm": {
    "url": "https://www.youtube.com/watch?v=M9cGHdVbNXI",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "operation-y-and-shuriks-other-adventures": {
    "url": "https://www.youtube.com/watch?v=7ICl3sPny94",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "kin-dza-dza": {
    "url": "https://www.youtube.com/watch?v=EYHv8eJrW2Y",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-color-of-pomegranates": {
    "url": "https://www.youtube.com/watch?v=9XN3vgj2za4",
    "platform": "YouTube",
    "label": "parajanovtv",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "the-snow-queen": {
    "url": "https://www.youtube.com/watch?v=Qp8ZhJqzABs",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-tale-of-tsar-saltan": {
    "url": "https://www.youtube.com/watch?v=f0Sfwa9VqT8",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "andrei-rublev": {
    "url": "https://www.youtube.com/watch?v=je75FDjcUP4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "alexander-nevsky": {
    "url": "https://www.youtube.com/watch?v=IKskdbazW7w",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "ivan-the-terrible-part-i": {
    "url": "https://www.youtube.com/watch?v=ZYOxxp_EVxc",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "i-am-cuba": {
    "url": "https://www.youtube.com/watch?v=Y3HpI898dwg",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "white-sun-of-the-desert": {
    "url": "https://www.youtube.com/watch?v=GqnqFhc9aho",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "ivan-vasilievich-changes-profession": {
    "url": "https://www.youtube.com/watch?v=TQ8onQu5QKY",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "gentlemen-of-fortune": {
    "url": "https://www.youtube.com/watch?v=8tJPKSz6Gaw",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "mimino": {
    "url": "https://www.youtube.com/watch?v=GgFLr2bjUNM",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "autumn-marathon": {
    "url": "https://www.youtube.com/watch?v=deEuVTAAzbg",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "carnival-night": {
    "url": "https://www.youtube.com/watch?v=fEntSqfPC0g",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "shadows-of-forgotten-ancestors": {
    "url": "https://www.youtube.com/watch?v=1EpSSmcusUI",
    "platform": "YouTube",
    "label": "Oleksandr Dovzhenko Centre",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "tale-of-tales": {
    "url": "https://www.youtube.com/watch?v=vTowzpTwv4s",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-mystery-of-the-third-planet": {
    "url": "https://www.youtube.com/watch?v=HZodexUkiDI",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "hamlet": {
    "url": "https://www.youtube.com/watch?v=eQ9hWxJVXgw",
    "platform": "YouTube",
    "label": "Добрый BorisAV",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "ivan-the-terrible-part-ii": {
    "url": "https://www.youtube.com/watch?v=i5g-Ss9BDR4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "a-cruel-romance": {
    "url": "https://www.youtube.com/watch?v=4naOrjRiTnc",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "a-railway-station-for-two": {
    "url": "https://www.youtube.com/watch?v=bUya5DBvw_g",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "hussar-ballad": {
    "url": "https://www.youtube.com/watch?v=929O4WzLRDg",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-garage": {
    "url": "https://www.youtube.com/watch?v=Xqsa4u00GXM",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "wings": {
    "url": "https://www.youtube.com/watch?v=lO6f6nO5HB4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "welcome-or-no-trespassing": {
    "url": "https://www.youtube.com/watch?v=e-r9XNmqQHk",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "fate-of-a-man": {
    "url": "https://www.youtube.com/watch?v=ov7bKyahGL4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-dawns-here-are-quiet": {
    "url": "https://www.youtube.com/watch?v=wk6TCpXjPFU",
    "platform": "YouTube",
    "label": "Gorky Film Studio official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "sadko": {
    "url": "https://www.youtube.com/watch?v=zedi4fgeMeI",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "ilya-muromets": {
    "url": "https://www.youtube.com/watch?v=pOhiBtmU-PE",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "viy": {
    "url": "https://www.youtube.com/watch?v=Amh3uudVMBo",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "cheburashka-and-gena-the-crocodile": {
    "url": "https://www.youtube.com/watch?v=aMHFMdAaBTQ",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "winnie-the-pooh": {
    "url": "https://www.youtube.com/watch?v=MYcmEVJIVoo",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "earth": {
    "url": "https://archive.org/details/two-hours-of-russian-special-military-operation-ukraine-war-music",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "arsenal": {
    "url": "https://archive.org/details/BELARUSTV_20251123_113000",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "strike": {
    "url": "https://archive.org/details/stachka",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "october-ten-days-that-shook-the-world": {
    "url": "https://archive.org/details/fra.video._skCEmnjDyc",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "mother": {
    "url": "https://archive.org/details/RUSSIA1_20260107_213000_Krugi_na_vode",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "the-end-of-st-petersburg": {
    "url": "https://archive.org/details/VsevolodPudovkinTheEndOfSt.Petersburg1927",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "aelita": {
    "url": "https://archive.org/details/BELARUSTV_20220924_160500",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "bed-and-sofa": {
    "url": "https://archive.org/details/bed-and-sofa-tretya-meshchanskaya-1927",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "chapaev": {
    "url": "https://www.youtube.com/watch?v=vv1QJ9g_yYc",
    "platform": "YouTube",
    "label": "Soviet Russian Films",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "jolly-fellows": {
    "url": "https://www.youtube.com/watch?v=chDRXQ77IgA",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "brief-encounters": {
    "url": "https://www.youtube.com/watch?v=Qaj3RRFNP5c",
    "platform": "YouTube",
    "label": "Internet Archive",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "kidnapping-caucasian-style": {
    "url": "https://www.youtube.com/watch?v=0f1LxDfNpv0",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-twelve-chairs": {
    "url": "https://www.youtube.com/watch?v=P8t2dbJ7YXY",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "walking-the-streets-of-moscow": {
    "url": "https://www.youtube.com/watch?v=vbjs5zfxDMs",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "afonya": {
    "url": "https://www.youtube.com/watch?v=L9HATyYkZLs",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "love-and-doves": {
    "url": "https://www.youtube.com/watch?v=CLjLLHDUiiA",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "an-ordinary-miracle": {
    "url": "https://www.youtube.com/watch?v=gZiKrWSzNBo",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "that-same-munchausen": {
    "url": "https://www.youtube.com/watch?v=OWB4k-YXJUM",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "heart-of-a-dog": {
    "url": "https://www.youtube.com/watch?v=FeGuBXYLbug",
    "platform": "YouTube",
    "label": "Lenfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "liberation": {
    "url": "https://www.youtube.com/watch?v=GZlzMhfx2hQ",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "they-fought-for-their-country": {
    "url": "https://www.youtube.com/watch?v=xfUlR_nuBb4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "belorussian-station": {
    "url": "https://www.youtube.com/watch?v=AafJinhS1fc",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "twenty-days-without-war": {
    "url": "https://www.youtube.com/watch?v=Xd8cptrLhm8",
    "platform": "YouTube",
    "label": "Первый канал ЦТ СССР",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "an-unfinished-piece-for-mechanical-piano": {
    "url": "https://www.youtube.com/watch?v=0OXkvpVCZEA",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "a-slave-of-love": {
    "url": "https://www.youtube.com/watch?v=majTxmCiw5k",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "oblomov": {
    "url": "https://www.youtube.com/watch?v=Q1zIasC2Og8",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "at-home-among-strangers": {
    "url": "https://www.youtube.com/watch?v=e0ECy37ayUw",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "siberiade": {
    "url": "https://www.youtube.com/watch?v=6P5Nf7xzXS0",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-lady-with-the-dog": {
    "url": "https://www.youtube.com/watch?v=qtIzBPAbCyg",
    "platform": "YouTube",
    "label": "Gevorg Vardanyan",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "king-lear": {
    "url": "https://www.youtube.com/watch?v=BqS1V41MjFQ",
    "platform": "YouTube",
    "label": "Кино Советской Эпохи",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "my-friend-ivan-lapshin": {
    "url": "https://www.youtube.com/watch?v=SnS5xz_XniI",
    "platform": "YouTube",
    "label": "Кино Советской Эпохи",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "letter-never-sent": {
    "url": "https://www.youtube.com/watch?v=qPScCOavuY8",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "repentance": {
    "url": "https://www.youtube.com/watch?v=bIIb5wUzjdc",
    "platform": "YouTube",
    "label": "RVISION",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "little-vera": {
    "url": "https://www.youtube.com/watch?v=E8MCiceJJdY",
    "platform": "YouTube",
    "label": "Gorky Film Studio official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-needle": {
    "url": "https://www.youtube.com/watch?v=UFEMle60E-4",
    "platform": "YouTube",
    "label": "UNESCO Almaty",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "assa": {
    "url": "https://www.youtube.com/watch?v=1Plo-PLxVg4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "morozko": {
    "url": "https://www.youtube.com/watch?v=TESoWRfVPCc",
    "platform": "YouTube",
    "label": "Gorky Film Studio official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "ruslan-and-lyudmila": {
    "url": "https://www.youtube.com/watch?v=hXz4dKq0Cps",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "scarlet-sails": {
    "url": "https://www.youtube.com/watch?v=5YzwW4hxrx4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "nu-pogodi": {
    "url": "https://www.youtube.com/watch?v=jlyzTjzseOk",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-scarlet-flower": {
    "url": "https://www.youtube.com/watch?v=1FtcZy6fow0",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-bremen-town-musicians": {
    "url": "https://www.youtube.com/watch?v=EZ70fF0htjQ",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "planet-of-storms": {
    "url": "https://www.youtube.com/watch?v=IC1J_ZprwJs",
    "platform": "YouTube",
    "label": "WonderLife",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "storm-over-asia": {
    "url": "https://www.youtube.com/watch?v=VjbHu-yubKY",
    "platform": "YouTube",
    "label": "Классика советского кино",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  }
};
