// AUTO-GENERATED by scripts/find-watch-links.ts — do not edit by hand.
// Concrete free/legal watch URLs per film, with honest trust levels.

export type WatchLink = {
  url: string;
  sourceType: string;
  label: string;
  platform: string;
  rightsNote: string;
};

export const watchLinks: Record<string, WatchLink> = {
  "the-cranes-are-flying": {
    "url": "https://www.youtube.com/watch?v=2rINnJat-5k",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "solaris": {
    "url": "https://www.youtube.com/watch?v=Z8ZhQPaw4rE",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "hedgehog-in-the-fog": {
    "url": "https://www.youtube.com/watch?v=mQqgViGenvk",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "battleship-potemkin": {
    "url": "https://www.youtube.com/watch?v=a_bkBbrdyyw",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "man-with-a-movie-camera": {
    "url": "https://www.youtube.com/watch?v=U1bgnBLqMyg",
    "platform": "YouTube",
    "label": "kinoglaz",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "ballad-of-a-soldier": {
    "url": "https://www.youtube.com/watch?v=Vsnius8Ka_I",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "war-and-peace": {
    "url": "https://www.youtube.com/watch?v=V-SAh4jdssA",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "stalker": {
    "url": "https://www.youtube.com/watch?v=Q3hBLv-HLEc",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "ivans-childhood": {
    "url": "https://www.youtube.com/watch?v=6Lnb1bI0VIk",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "the-mirror": {
    "url": "https://www.youtube.com/watch?v=NrMINC5xjMs",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "come-and-see": {
    "url": "https://www.youtube.com/watch?v=zjIiApN6cfg",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-ascent": {
    "url": "https://www.youtube.com/watch?v=v21lQ449T3Y",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "dersu-uzala": {
    "url": "https://www.youtube.com/watch?v=sFaL03SKEzE",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "the-irony-of-fate": {
    "url": "https://www.youtube.com/watch?v=ms5Ga6kNvHM",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "moscow-does-not-believe-in-tears": {
    "url": "https://www.youtube.com/watch?v=NTWA_7-ld_U",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "office-romance": {
    "url": "https://www.youtube.com/watch?v=mi4gQMDgB_g",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "the-diamond-arm": {
    "url": "https://www.youtube.com/watch?v=MkHiu9fD820",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "operation-y-and-shuriks-other-adventures": {
    "url": "https://www.youtube.com/watch?v=m3n4LptYWNo",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "kin-dza-dza": {
    "url": "https://www.youtube.com/watch?v=EYHv8eJrW2Y",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-color-of-pomegranates": {
    "url": "https://www.youtube.com/watch?v=9XN3vgj2za4",
    "platform": "YouTube",
    "label": "parajanovtv",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "the-snow-queen": {
    "url": "https://www.youtube.com/watch?v=g0VSkAoocmM",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "the-tale-of-tsar-saltan": {
    "url": "https://www.youtube.com/watch?v=f0Sfwa9VqT8",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "andrei-rublev": {
    "url": "https://www.youtube.com/watch?v=je75FDjcUP4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "alexander-nevsky": {
    "url": "https://www.youtube.com/watch?v=Gq4PaJfod4w",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "ivan-the-terrible-part-i": {
    "url": "https://www.youtube.com/watch?v=ZYOxxp_EVxc",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "i-am-cuba": {
    "url": "https://www.youtube.com/watch?v=Y3HpI898dwg",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "white-sun-of-the-desert": {
    "url": "https://www.youtube.com/watch?v=Auj_u7wEyw8",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "ivan-vasilievich-changes-profession": {
    "url": "https://www.youtube.com/watch?v=l7eIIIPBNUc",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "gentlemen-of-fortune": {
    "url": "https://www.youtube.com/watch?v=XukcyHljlCE",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "mimino": {
    "url": "https://www.youtube.com/watch?v=GgFLr2bjUNM",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "autumn-marathon": {
    "url": "https://www.youtube.com/watch?v=X4e4-tYlHwo",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "carnival-night": {
    "url": "https://www.youtube.com/watch?v=TxrtUnWBCeI",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "shadows-of-forgotten-ancestors": {
    "url": "https://www.youtube.com/watch?v=1EpSSmcusUI",
    "platform": "YouTube",
    "label": "Oleksandr Dovzhenko Centre",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "tale-of-tales": {
    "url": "https://www.youtube.com/watch?v=vTowzpTwv4s",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-mystery-of-the-third-planet": {
    "url": "https://www.youtube.com/watch?v=QSOiC5NfZcM",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "hamlet": {
    "url": "https://www.youtube.com/watch?v=OzN1isLYc_A",
    "platform": "YouTube",
    "label": "Shakespeare Network",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "ivan-the-terrible-part-ii": {
    "url": "https://www.youtube.com/watch?v=vnNgoS8VsoQ",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "a-cruel-romance": {
    "url": "https://www.youtube.com/watch?v=_394TmF4DKY",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "a-railway-station-for-two": {
    "url": "https://www.youtube.com/watch?v=bUya5DBvw_g",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "hussar-ballad": {
    "url": "https://www.youtube.com/watch?v=vDtxO70AQZ4",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "the-garage": {
    "url": "https://www.youtube.com/watch?v=VahEhy4HJu4",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "wings": {
    "url": "https://www.youtube.com/watch?v=lO6f6nO5HB4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "welcome-or-no-trespassing": {
    "url": "https://www.youtube.com/watch?v=X-4LQzazwUs",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "fate-of-a-man": {
    "url": "https://www.youtube.com/watch?v=O7xGW8UvBKQ",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "the-dawns-here-are-quiet": {
    "url": "https://www.youtube.com/watch?v=wk6TCpXjPFU",
    "platform": "YouTube",
    "label": "Gorky Film Studio official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "sadko": {
    "url": "https://www.youtube.com/watch?v=zedi4fgeMeI",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "ilya-muromets": {
    "url": "https://www.youtube.com/watch?v=pOhiBtmU-PE",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "viy": {
    "url": "https://www.youtube.com/watch?v=4YmQn6q36HQ",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "cheburashka-and-gena-the-crocodile": {
    "url": "https://www.youtube.com/watch?v=aMHFMdAaBTQ",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "winnie-the-pooh": {
    "url": "https://www.youtube.com/watch?v=5GE1DmY-qdI",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "earth": {
    "url": "https://archive.org/details/1930-earth",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "arsenal": {
    "url": "https://archive.org/details/arsenal-eng-sub",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "strike": {
    "url": "https://archive.org/details/strike-eisenstein-1925-english-intertitles-hd-quality",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "october-ten-days-that-shook-the-world": {
    "url": "https://archive.org/details/october1928",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "mother": {
    "url": "https://archive.org/details/mother-1926",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "the-end-of-st-petersburg": {
    "url": "https://archive.org/details/VsevolodPudovkinTheEndOfSt.Petersburg1927",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "aelita": {
    "url": "https://archive.org/details/aelita-queen-of-mars-1924_202506",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "bed-and-sofa": {
    "url": "https://archive.org/details/bed-and-sofa-tretya-meshchanskaya-1927",
    "platform": "Internet Archive",
    "label": "Internet Archive",
    "sourceType": "PUBLIC_REPOSITORY",
    "rightsNote": "Public-domain copy hosted on the Internet Archive."
  },
  "chapaev": {
    "url": "https://www.youtube.com/watch?v=vv1QJ9g_yYc",
    "platform": "YouTube",
    "label": "Soviet Russian Films",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "jolly-fellows": {
    "url": "https://www.youtube.com/watch?v=chDRXQ77IgA",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "brief-encounters": {
    "url": "https://www.youtube.com/watch?v=Qaj3RRFNP5c",
    "platform": "YouTube",
    "label": "Internet Archive",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "kidnapping-caucasian-style": {
    "url": "https://www.youtube.com/watch?v=8KYUSLtXJyo",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "the-twelve-chairs": {
    "url": "https://www.youtube.com/watch?v=d5GSQY4Lt-E",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "walking-the-streets-of-moscow": {
    "url": "https://www.youtube.com/watch?v=vbjs5zfxDMs",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "afonya": {
    "url": "https://www.youtube.com/watch?v=IszoiMr-nBs",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "love-and-doves": {
    "url": "https://www.youtube.com/watch?v=CLjLLHDUiiA",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "an-ordinary-miracle": {
    "url": "https://www.youtube.com/watch?v=gZiKrWSzNBo",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "that-same-munchausen": {
    "url": "https://www.youtube.com/watch?v=OWB4k-YXJUM",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "heart-of-a-dog": {
    "url": "https://www.youtube.com/watch?v=H66k6jHiMfw",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "liberation": {
    "url": "https://www.youtube.com/watch?v=GZlzMhfx2hQ",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "they-fought-for-their-country": {
    "url": "https://www.youtube.com/watch?v=gOxKScK1KOU",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "belorussian-station": {
    "url": "https://www.youtube.com/watch?v=zX3IVNrx1Zs",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "twenty-days-without-war": {
    "url": "https://www.youtube.com/watch?v=Xd8cptrLhm8",
    "platform": "YouTube",
    "label": "Первый канал ЦТ СССР",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "an-unfinished-piece-for-mechanical-piano": {
    "url": "https://www.youtube.com/watch?v=XNrAhFUWimI",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "a-slave-of-love": {
    "url": "https://www.youtube.com/watch?v=Otr_5MVh_00",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "oblomov": {
    "url": "https://www.youtube.com/watch?v=LxEFja8NYac",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "at-home-among-strangers": {
    "url": "https://www.youtube.com/watch?v=59tzk9h-nfM",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "siberiade": {
    "url": "https://www.youtube.com/watch?v=6P5Nf7xzXS0",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-lady-with-the-dog": {
    "url": "https://www.youtube.com/watch?v=_8MwK0EvJ5A",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "king-lear": {
    "url": "https://www.youtube.com/watch?v=RDOm18j4dE0",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "my-friend-ivan-lapshin": {
    "url": "https://www.youtube.com/watch?v=SnS5xz_XniI",
    "platform": "YouTube",
    "label": "Кино Советской Эпохи",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "letter-never-sent": {
    "url": "https://www.youtube.com/watch?v=qPScCOavuY8",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "repentance": {
    "url": "https://www.youtube.com/watch?v=bIIb5wUzjdc",
    "platform": "YouTube",
    "label": "RVISION",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "little-vera": {
    "url": "https://www.youtube.com/watch?v=E8MCiceJJdY",
    "platform": "YouTube",
    "label": "Gorky Film Studio official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-needle": {
    "url": "https://www.youtube.com/watch?v=UFEMle60E-4",
    "platform": "YouTube",
    "label": "UNESCO Almaty",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "assa": {
    "url": "https://www.youtube.com/watch?v=1Plo-PLxVg4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "morozko": {
    "url": "https://www.youtube.com/watch?v=hw2DN4335hU",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "ruslan-and-lyudmila": {
    "url": "https://www.youtube.com/watch?v=hXz4dKq0Cps",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "scarlet-sails": {
    "url": "https://www.youtube.com/watch?v=Mhz-bn1ys4Y",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "nu-pogodi": {
    "url": "https://www.youtube.com/watch?v=jlyzTjzseOk",
    "platform": "YouTube",
    "label": "Soyuzmultfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-scarlet-flower": {
    "url": "https://www.youtube.com/watch?v=GqSyfN5bOh0",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "the-bremen-town-musicians": {
    "url": "https://www.youtube.com/watch?v=ekdWS1c3-bg",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "planet-of-storms": {
    "url": "https://www.youtube.com/watch?v=-VTF23EFvEM",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "beware-of-the-car": {
    "url": "https://www.youtube.com/watch?v=PGr-NddVue0",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-forty-first": {
    "url": "https://www.youtube.com/watch?v=USSRE6d6qcA",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "clear-sky": {
    "url": "https://www.youtube.com/watch?v=rTx1o8tTgJk",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "agony": {
    "url": "https://www.youtube.com/watch?v=Ll1Wdob2P1E",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "uncle-vanya": {
    "url": "https://www.youtube.com/watch?v=EF3A9mmRzGc",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "nine-days-of-one-year": {
    "url": "https://www.youtube.com/watch?v=HGf-cZZDH3s",
    "platform": "YouTube",
    "label": "Mosfilm (English subtitles)",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on Mosfilm's official channel, with English subtitles."
  },
  "five-evenings": {
    "url": "https://www.youtube.com/watch?v=p9mC85IOkDc",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "kinfolk": {
    "url": "https://www.youtube.com/watch?v=du-1H8aLtj8",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "dont-grieve": {
    "url": "https://www.youtube.com/watch?v=M6KxVntypo4",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "the-stone-flower": {
    "url": "https://www.youtube.com/watch?v=k6QNtZRtsjM",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "white-bim-black-ear": {
    "url": "https://www.youtube.com/watch?v=tItkWn6bLlg",
    "platform": "YouTube",
    "label": "Gorky Film Studio official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "well-live-till-monday": {
    "url": "https://www.youtube.com/watch?v=G7rbFy5EYwU",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "kingdom-of-crooked-mirrors": {
    "url": "https://www.youtube.com/watch?v=bWvdNYJfxHM",
    "platform": "YouTube",
    "label": "Gorky Film Studio official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "fire-water-and-brass-pipes": {
    "url": "https://www.youtube.com/watch?v=d1L8NEdYLKU",
    "platform": "YouTube",
    "label": "Soviet and Russian Cinema",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "the-golden-antelope": {
    "url": "https://www.youtube.com/watch?v=qHe46Ry69rQ",
    "platform": "YouTube",
    "label": "Soviet animation collection",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "to-kill-a-dragon": {
    "url": "https://www.youtube.com/watch?v=qGbN7cUgJlo",
    "platform": "YouTube",
    "label": "Mosfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "don-quixote": {
    "url": "https://www.youtube.com/watch?v=aebHLrhyz-c",
    "platform": "YouTube",
    "label": "English-subtitled upload",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload with English subtitles; not the rights holder's own channel."
  },
  "trial-on-the-road": {
    "url": "https://www.youtube.com/watch?v=2rHFVO87TyY",
    "platform": "YouTube",
    "label": "Кино Советской Эпохи",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "the-star-of-captivating-happiness": {
    "url": "https://www.youtube.com/watch?v=lBQVWKVXR70",
    "platform": "YouTube",
    "label": "Lenfilm official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "dead-season": {
    "url": "https://www.youtube.com/watch?v=Lz0neaJrk8E",
    "platform": "YouTube",
    "label": "КиноАрхив",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  },
  "the-magic-lamp-of-aladdin": {
    "url": "https://www.youtube.com/watch?v=y_Oy9MHrEMI",
    "platform": "YouTube",
    "label": "Gorky Film Studio official channel",
    "sourceType": "OFFICIAL",
    "rightsNote": "Free to watch on the studio's official channel."
  },
  "storm-over-asia": {
    "url": "https://www.youtube.com/watch?v=VjbHu-yubKY",
    "platform": "YouTube",
    "label": "Классика советского кино",
    "sourceType": "UNVERIFIED",
    "rightsNote": "Unofficial upload, provided as a convenience; not the rights holder's own channel."
  }
};
