import fs from "node:fs";
import path from "node:path";
import { createPrismaClient } from "../lib/prisma";
import { getJson } from "./ingest/http";
import { fetchCommonsImage, type CommonsImage } from "./ingest/commons";

// Best-effort image enrichment. Pulls freely-licensed Wikimedia Commons images
// (license-checked in commons.ts) for films (by their Wikidata Q-id) and people
// (resolved from Wikidata by name, restricted to film figures), and writes a
// committed data file (lib/imageData.ts) that the seed turns into ImageAssets.
// Re-runnable; only free-licensed images are kept, everything else is skipped.

try {
  process.loadEnvFile();
} catch {
  /* env optional */
}

type Entity = { claims?: Record<string, { mainsnak?: { datavalue?: { value?: unknown } } }[]> };

async function imageFileForEntity(qid: string): Promise<string | undefined> {
  const data = await getJson<{ entities: Record<string, Entity> }>(
    `https://www.wikidata.org/wiki/Special:EntityData/${qid}.json`,
  );
  const p18 = data.entities[qid]?.claims?.["P18"]?.[0]?.mainsnak?.datavalue?.value;
  return typeof p18 === "string" ? p18 : undefined;
}

// Resolve a person's Wikidata Q-id by name, but only accept entities that look
// like film figures, to avoid wrong-name matches.
const FILM_ROLE = /actor|actress|director|film|screenwriter|animator|cinematograph|producer/i;
async function resolvePersonQid(name: string): Promise<string | undefined> {
  const url =
    `https://www.wikidata.org/w/api.php?action=wbsearchentities&format=json` +
    `&type=item&language=en&limit=5&search=${encodeURIComponent(name)}`;
  const data = await getJson<{ search?: { id: string; description?: string }[] }>(url);
  const hit = (data.search ?? []).find((s) => FILM_ROLE.test(s.description ?? ""));
  return hit?.id;
}

type ImageRecord = {
  url: string;
  descriptionUrl: string;
  licenseName: string;
  licenseUrl?: string;
  attribution: string;
};
const toRecord = (img: CommonsImage): ImageRecord => ({
  url: img.url,
  descriptionUrl: img.descriptionUrl,
  licenseName: img.licenseName,
  licenseUrl: img.licenseUrl,
  attribution: img.attribution,
});

const prisma = createPrismaClient();

async function main() {
  const films = await prisma.film.findMany({
    where: { wikidataId: { not: null } },
    select: { slug: true, title: true, wikidataId: true },
  });
  const people = await prisma.person.findMany({ select: { slug: true, name: true } });

  const filmImages: Record<string, ImageRecord> = {};
  const personImages: Record<string, ImageRecord> = {};

  console.log(`Films: ${films.length}, People: ${people.length}`);

  for (const f of films) {
    try {
      const file = f.wikidataId ? await imageFileForEntity(f.wikidataId) : undefined;
      const img = file ? await fetchCommonsImage(file) : null;
      if (img) {
        filmImages[f.slug] = toRecord(img);
        console.log(`  film  ✓ ${f.slug} [${img.licenseName}]`);
      } else {
        console.log(`  film  – ${f.slug} (no free image)`);
      }
    } catch (e) {
      console.log(`  film  ! ${f.slug}: ${(e as Error).message}`);
    }
  }

  for (const p of people) {
    try {
      const qid = await resolvePersonQid(p.name);
      const file = qid ? await imageFileForEntity(qid) : undefined;
      const img = file ? await fetchCommonsImage(file) : null;
      if (img) {
        personImages[p.slug] = toRecord(img);
        console.log(`  person ✓ ${p.slug} [${img.licenseName}]`);
      }
    } catch {
      /* best-effort: skip people we can't resolve */
    }
  }

  const out =
    `// AUTO-GENERATED by scripts/fetch-images.ts — do not edit by hand.\n` +
    `// Freely-licensed Wikimedia Commons images for films and people.\n\n` +
    `export type ImageRecord = {\n` +
    `  url: string;\n  descriptionUrl: string;\n  licenseName: string;\n` +
    `  licenseUrl?: string;\n  attribution: string;\n};\n\n` +
    `export const filmImages: Record<string, ImageRecord> = ${JSON.stringify(filmImages, null, 2)};\n\n` +
    `export const personImages: Record<string, ImageRecord> = ${JSON.stringify(personImages, null, 2)};\n`;

  fs.writeFileSync(path.join(process.cwd(), "lib", "imageData.ts"), out);
  console.log(
    `\nWrote lib/imageData.ts — ${Object.keys(filmImages).length} film images, ${Object.keys(personImages).length} person images.`,
  );
}

main()
  .catch((e) => {
    console.error("fetch-images failed:", e instanceof Error ? e.message : e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
