// Re-applies the editorial text (summary / context / impact / themes) from
// scripts/newFilmsData.ts onto the existing lib/filmsExtra.ts, preserving all
// Wikidata-derived facts (Q-id, original title, runtime, etc.). No network.
//
//   npx tsx scripts/mergeEditorial.ts
//
import { writeFileSync } from "node:fs";
import { newFilms } from "./newFilmsData";
import { extraFilms } from "../lib/filmsExtra";

const bySlug = Object.fromEntries(newFilms.map((f) => [f.slug, f]));

let updated = 0;
for (const e of extraFilms as any[]) {
  const n = bySlug[e.slug];
  if (!n) {
    console.log(`‼ no editorial for ${e.slug}`);
    continue;
  }
  e.summary = n.summary;
  e.context = n.context;
  if (n.impact) e.impact = n.impact;
  else delete e.impact;
  e.themes = n.themes;
  updated += 1;
}

const header = `// AUTO-GENERATED by scripts/buildExtraFilms.ts — do not edit by hand.
// Tier 1–4 catalogue expansion (${extraFilms.length} films). Editorial text is ORIGINAL
// (see scripts/newFilmsData.ts); factual metadata enriched from Wikidata.
import type { SeedFilm } from "./films";

export const extraFilms: SeedFilm[] = `;
writeFileSync(
  new URL("../lib/filmsExtra.ts", import.meta.url),
  `${header}${JSON.stringify(extraFilms, null, 2)};\n`,
  "utf8",
);
console.log(`Merged editorial into lib/filmsExtra.ts (${updated} films).`);
