// Patches the 6 films whose enrichment failed on a network drop at the end of
// the build run. Fetches each by exact Q-id and merges metadata into the
// existing lib/filmsExtra.ts, preserving the 66 already-good entries.
//
//   npx tsx scripts/patchExtraFilms.ts
//
import { writeFileSync } from "node:fs";
import { extraFilms } from "../lib/filmsExtra";

const UA = {
  "User-Agent":
    "Kotfilm/1.0 (educational Soviet-cinema guide; contact bourgeoisjacob@gmail.com)",
};
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
async function getj(u: string): Promise<any> {
  for (let i = 0; i < 5; i++) {
    try {
      const r = await fetch(u, { headers: UA });
      return await r.json();
    } catch {
      await sleep(1000);
    }
  }
  return null;
}
async function ent(q: string) {
  const j = await getj(`https://www.wikidata.org/wiki/Special:EntityData/${q}.json`);
  return j?.entities?.[q] ?? null;
}

// slug -> Q-id (resolved earlier via search / Wikipedia pageprops)
const PIN: Record<string, string> = {
  "ruslan-and-lyudmila": "Q2388002",
  "scarlet-sails": "Q1171515",
  "nu-pogodi": "Q4327877",
  "the-scarlet-flower": "Q3209019",
  "the-bremen-town-musicians": "Q4096274",
  "planet-of-storms": "Q1895210",
};
const RUNTIME_CLEAR = new Set(["nu-pogodi"]); // series total — unusable

async function main() {
  for (const f of extraFilms as any[]) {
    const qid = PIN[f.slug];
    if (!qid) continue;
    const e = await ent(qid);
    await sleep(120);
    if (!e) {
      console.log(`‼ ${f.slug}: still no entity`);
      continue;
    }
    f.wikidataId = qid;
    const original =
      e.claims?.P1476?.[0]?.mainsnak?.datavalue?.value?.text ??
      e.labels?.ru?.value ??
      e.labels?.uk?.value;
    if (original) f.original = original;
    const rt = e.claims?.P2047?.[0]?.mainsnak?.datavalue?.value?.amount;
    if (rt && !RUNTIME_CLEAR.has(f.slug)) f.runtime = Math.round(Number(rt));
    const wTitle = e.sitelinks?.enwiki?.title;
    if (wTitle)
      f.wikipediaUrl = `https://en.wikipedia.org/wiki/${encodeURIComponent(
        wTitle.replace(/ /g, "_"),
      )}`;
    console.log(
      `ok ${f.slug.padEnd(28)} ${qid.padEnd(11)} rt=${f.runtime ?? "-"} ${f.original ?? ""}`,
    );
  }

  const header = `// AUTO-GENERATED by scripts/buildExtraFilms.ts — do not edit by hand.
// Tier 1–4 catalogue expansion (${extraFilms.length} films). Editorial text is ORIGINAL
// (see scripts/newFilmsData.ts); factual metadata enriched from Wikidata.
import type { SeedFilm } from "./films";

export const extraFilms: SeedFilm[] = `;
  writeFileSync(
    new URL("../lib/filmsExtra.ts", import.meta.url),
    `${header}${JSON.stringify(extraFilms, null, 2)};\n`,
    "utf8",
  );
  console.log("\nPatched lib/filmsExtra.ts");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
